Terraform project type
Co-authored-by: Kyle Harding <kyle@balena.io>

change-type: patch

diff --git a/flowzone.yml b/flowzone.yml
--- a/flowzone.yml
+++ b/flowzone.yml
@@ -529,6 +529,50 @@
     name: Get caller identity (AWS/whoami)
     run: aws sts get-caller-identity
 
+  - &updateKubeconfig
+    name: Update kubeconfig
+    run: |
+      aws eks update-kubeconfig --name $(echo "${KUBE_CTX}" | awk -F'/' '{print $2}')
+
+  - &convenienceFunctions
+    name: Convenience functions
+    id: functions
+    run: |
+      EOF="$(openssl rand -hex 16)"
+
+      # https://sre.google/sre-book/addressing-cascading-failures/
+      with_backoff="$(mktemp)"
+      cat << $EOF > "${with_backoff}"
+      function with_backoff() {
+          local max_attempts=\${ATTEMPTS-3}
+          local timeout=\${TIMEOUT-2}
+          local attempt=0
+          local exitCode=0
+          set +e
+          while [[ \$attempt < \$max_attempts ]]; do
+              "\$@"
+              exitCode=\$?
+              [[ \$exitCode == 0 ]] && break
+              echo "Failure! Retrying in \$timeout.." 1>&2
+              sleep "\$timeout"
+              attempt=\$(( attempt + 1 ))
+              timeout=\$(( timeout * 2 ))
+          done
+          [[ \$exitCode != 0 ]] && echo "You've failed me for the last time! (\$*)" 1>&2
+          set -e
+          return \$exitCode
+      }
+      $EOF
+      echo "with_backoff=${with_backoff}" >> $GITHUB_OUTPUT
+
+  - &randomDelay
+    name: Random delay
+    run: |
+      DELAY=${DELAY-5}
+      random=$(((RANDOM % DELAY) + 1))
+      echo "::notice::sleeping for ${random}s"
+      sleep "${random}s"
+
 name: Flowzone
 
 on:
@@ -596,7 +640,50 @@ on:
         required: false
         default: "${{ vars.AWS_IAM_ROLE || '' }}"
       cloudformation_templates:
-        description: "AWS CloudFormation templates to deploy"
+        description: |
+          AWS CloudFormation templates to deploy (e.g.)
+
+          ```
+          {
+            "stacks": [
+              {
+                "name": "foo",
+                "template": "aws/bar.yaml",
+                "tags": [
+                  "Name=foo",
+                  "Environment=${FOO}"
+                ],
+                "capabilities": [
+                  "CAPABILITY_IAM",
+                  "CAPABILITY_NAMED_IAM"
+                ]
+              },
+              ...
+            ]
+          }
+          ```
+
+          * assumes `aws/bar.yaml` exists.
+          * `${ENVVARS}` injected at runtime from `vars` and `secrets` contexts
+        type: string
+        required: false
+        default: ""
+      terraform_projects:
+        description: |
+          Terraform projects to deploy (e.g.)
+
+          ```
+          {
+            "projects": [
+              {
+                "main_tf": "terraform/foo"
+              }
+            ]
+          }
+          ```
+
+          * assumes `terraform/foo/main.tf` exists
+          * GitHub `vars` and `secrets` contexts injected into TF plan/apply steps
         type: string
         required: false
         default: ""
@@ -1744,8 +1831,7 @@ jobs:
     if: |
       !failure() && !cancelled() &&
       needs.versioned_source.result == 'success' &&
-      inputs.cloudformation_templates != '' &&
-      github.event.pull_request.head.repo.full_name == github.repository
+      inputs.cloudformation_templates != ''
 
     <<: *customWorkingDirectory
 
@@ -1759,10 +1845,16 @@ jobs:
       - name: Validate CloudFormation input
         id: validate_json
         run: |
-          if echo '${{ inputs.cloudformation_templates }}' | jq -r
+          if echo '${{ inputs.cloudformation_templates }}' | jq -r .stacks
           then
+            if [[ '${{ github.event.pull_request.head.repo.full_name }}' != '${{ github.repository }}' ]]; then
+              echo '::warning:: CloudFormation stacks are skipped for external contributions.'
+              echo "enabled=false" >> $GITHUB_OUTPUT
+              exit 0
+            fi
             echo "enabled=true" >> $GITHUB_OUTPUT
           else
+            echo '::warning::invalid JSON or no CloudFormation stacks?'
             echo "enabled=false" >> $GITHUB_OUTPUT
           fi
 
@@ -1772,6 +1864,47 @@ jobs:
           stacks="$(echo '${{ inputs.cloudformation_templates }}' \
             | jq -r '.stacks[].name' | jq -Rcn '[inputs'])"
           echo "deploy=${stacks}" >> $GITHUB_OUTPUT
+
+  is_terraform:
+    name: Is Terraform
+    runs-on: ${{ fromJSON(inputs.runs_on) }}
+    timeout-minutes: ${{ fromJSON(inputs.jobs_timeout_minutes) }}
+    needs:
+      - versioned_source
+    if: |
+      !failure() && !cancelled() &&
+      needs.versioned_source.result == 'success' &&
+      inputs.terraform_projects != ''
+
+    <<: *customWorkingDirectory
+
+    outputs:
+      terraform: ${{ steps.validate_json.outputs.enabled }}
+      projects: ${{ steps.terraform_projects.outputs.deploy }}
+
+    steps:
+      - name: Validate Terraform input
+        id: validate_json
+        run: |
+          if echo '${{ inputs.terraform_projects }}' | jq -r .projects
+          then
+            if [[ '${{ github.event.pull_request.head.repo.full_name }}' != '${{ github.repository }}' ]]; then
+              echo '::warning:: Terraform projects are skipped for external contributions.'
+              echo "enabled=false" >> $GITHUB_OUTPUT
+              exit 0
+            fi
+            echo "enabled=true" >> $GITHUB_OUTPUT
+          else
+            echo '::warning::invalid JSON or no Terraform projects?'
+            echo "enabled=false" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Generate projects matrix
+        id: terraform_projects
+        run: |
+          projects="$(echo '${{ inputs.terraform_projects }}' \
+            | jq -r '.projects[].main_tf' | jq -Rcn '[inputs'])"
+          echo "deploy=${projects}" >> $GITHUB_OUTPUT
 
   ###################################################
   ## npm
@@ -3145,17 +3278,28 @@ jobs:
 
     <<: *customWorkingDirectory
 
+    env:
+      AWS_RETRY_MODE: adaptive
+      AWS_MAX_ATTEMPTS: 10
+      ATTEMPTS: 5
+      TIMEOUT: 3
+
     steps:
       - *checkoutVersionedSha
+      - *randomDelay # Why do people always forget that you need to add a little jitter?
       - *configureAWSCredentials
       - *getAWSCallerIdentity
+      - *convenienceFunctions
 
       - name: Create templates bucket
         id: make_bucket
         run: |
-          bucket="$(aws s3api list-buckets | jq -r '.Buckets[] | select(.Name=="${{ vars.AWS_S3_BUCKET }}").Name' || true)"
+          # If at first you don't succeed, back off exponentially.
+          source '${{ steps.functions.outputs.with_backoff }}'
+
+          bucket="$(with_backoff aws s3api list-buckets | jq -r '.Buckets[] | select(.Name=="${{ vars.AWS_S3_BUCKET }}").Name' || true)"
           if [[ -z "$bucket" ]]; then
-              result="$(aws s3 mb "s3://cfn-$(uuidgen)-${{ inputs.aws_region }}" --region '${{ inputs.aws_region }}')"
+              result="$(with_backoff aws s3 mb "s3://cfn-$(uuidgen)-${{ inputs.aws_region }}" --region '${{ inputs.aws_region }}')"
               bucket=${result#*:}
           fi
           echo "s3_bucket=${bucket}" >> $GITHUB_OUTPUT
@@ -3203,14 +3347,18 @@ jobs:
 
       - name: Validate template
         run: |
-          aws cloudformation validate-template \
+          source '${{ steps.functions.outputs.with_backoff }}'
+
+          with_backoff aws cloudformation validate-template \
             --template-body 'file://${{ steps.shared.outputs.template_file }}'
 
       - name: Package template
         run: |
+          source '${{ steps.functions.outputs.with_backoff }}'
+
           mkdir -p "package/$(dirname '${{ steps.shared.outputs.template_file }}')"
 
-          aws cloudformation package \
+          with_backoff aws cloudformation package \
             --template-file '${{ steps.shared.outputs.template_file }}' \
             --s3-bucket '${{ steps.make_bucket.outputs.s3_bucket }}' \
             --output-template-file 'package/${{ steps.shared.outputs.template_file }}'
@@ -3227,23 +3375,27 @@ jobs:
       - name: Delete existing change set
         continue-on-error: true
         run: |
-          change_set_ids="$(aws cloudformation list-change-sets \
+          source '${{ steps.functions.outputs.with_backoff }}'
+
+          change_set_ids="$(with_backoff aws cloudformation list-change-sets \
             --stack-name '${{ matrix.stack }}' | jq -r '.Summaries[].ChangeSetId')"
 
           for id in ${change_set_ids}; do
-              pr_tag="$(aws cloudformation describe-change-set \
+              pr_tag="$(with_backoff aws cloudformation describe-change-set \
                 --change-set-name "${id}" \
                 --query Tags | jq -r '.[] | select(.Key=="github_pull_request").Value')"
 
               if [[ -n "$pr_tag" ]] && [[ "$pr_tag" == '${{ github.event.pull_request.number }}' ]]; then
-                  aws cloudformation delete-change-set --change-set-name "${id}"
+                  with_backoff aws cloudformation delete-change-set --change-set-name "${id}"
               fi
           done
 
       - name: Generate change set
         id: change_set
         run: |
-          result="$(aws cloudformation deploy \
+          source '${{ steps.functions.outputs.with_backoff }}'
+
+          result="$(with_backoff aws cloudformation deploy \
             --stack-name '${{ steps.shared.outputs.stack_name }}' \
             --template-file 'package/${{ steps.shared.outputs.template_file }}' \
             --s3-bucket '${{ steps.make_bucket.outputs.s3_bucket }}' \
@@ -3289,28 +3441,188 @@ jobs:
       needs.is_pr_merged.result != needs.is_pushed_tag.result &&
       needs.is_cloudformation.outputs.cloudformation == 'true'
 
+    env:
+      # https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-retries.html#cli-usage-retries-modes-adaptive
+      AWS_RETRY_MODE: adaptive
+      AWS_MAX_ATTEMPTS: 10
+      ATTEMPTS: 5
+      TIMEOUT: 3
+
     steps:
+      - *randomDelay
       - *configureAWSCredentials
       - *getAWSCallerIdentity
       - *waitForCloudFormation
+      - *convenienceFunctions
 
       - name: Execute change set
         run: |
-          change_set_ids="$(aws cloudformation list-change-sets \
+          source '${{ steps.functions.outputs.with_backoff }}'
+
+          change_set_ids="$(with_backoff aws cloudformation list-change-sets \
             --stack-name '${{ matrix.stack }}' \
             | jq -r '.Summaries[] | select(.ExecutionStatus=="AVAILABLE").ChangeSetId')"
 
           for id in ${change_set_ids}; do
-              pr_tag="$(aws cloudformation describe-change-set \
+              pr_tag="$(with_backoff aws cloudformation describe-change-set \
                 --change-set-name "${id}" \
                 --query Tags | jq -r '.[] | select(.Key=="github_pull_request").Value')"
 
               if [[ -n "$pr_tag" ]] && [[ "$pr_tag" == '${{ github.event.pull_request.number }}' ]]; then
-                  aws cloudformation execute-change-set --change-set-name "${id}"
+                  with_backoff aws cloudformation execute-change-set --change-set-name "${id}"
               fi
           done
 
       - *waitForCloudFormation
+
+  ###################################################
+  # Terraform
+  ###################################################
+
+  terraform_test:
+    name: Test Terraform
+    runs-on: ${{ fromJSON(inputs.runs_on) }}
+    strategy:
+      fail-fast: true
+      matrix:
+        project: ${{ fromJSON(needs.is_terraform.outputs.projects) }}
+    timeout-minutes: ${{ fromJSON(inputs.jobs_timeout_minutes) }}
+    needs:
+      - is_pr_open
+      - is_terraform
+      - versioned_source
+    if: |
+      !failure() && !cancelled() &&
+      needs.is_pr_open.result == 'success' &&
+      needs.is_terraform.outputs.terraform == 'true'
+
+    defaults:
+      run:
+        working-directory: ${{ matrix.project }}
+
+    env:
+      # TF state pointer
+      KUBE_CTX: ${{ vars.KUBECTL_CONTEXT }}
+      KUBE_NAMESPACE: ${{ vars.KUBE_NAMESPACE }}
+      LOCK_TIMEOUT: 300s # wait for TF lock(s)
+
+    steps:
+      - *checkoutVersionedSha
+      - *randomDelay
+      - *configureAWSCredentials
+      - *getAWSCallerIdentity
+      - *updateKubeconfig
+
+      - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2
+        with:
+          terraform_wrapper: false
+          terraform_version: 1.3.9
+
+      - name: Terraform init
+        run: terraform init
+
+      - name: Terraform show
+        run: terraform show
+
+      - name: Terraform validate
+        run: terraform validate
+
+      - name: Terraform plan
+        env:
+          SECRETS_CONTEXT: ${{ toJson(secrets) }}
+          VARS_CONTEXT: ${{ toJson(vars) }}
+        run: |
+          set -a
+
+          trap 'rm -f .env "${json_plan}"' EXIT
+
+          to_envs() { jq -r "to_entries[] | \"\(.key)="\'"\(.value)"\'"\""; }
+
+          echo "${SECRETS_CONTEXT}" | to_envs > .env
+          echo "${VARS_CONTEXT}" | to_envs >> .env
+          source .env && rm -f .env
+
+          rc=0
+          terraform plan -lock-timeout=${LOCK_TIMEOUT} -detailed-exitcode || rc=$?
+          if [[ $rc -eq 1 ]]; then
+              false
+          fi
+
+          json_plan="$(mktemp)"
+          terraform plan -lock-timeout=${LOCK_TIMEOUT} -json > "${json_plan}"
+          msg=$(cat < "${json_plan}" | jq -rs '.[] | select(.type=="change_summary")."@message"')
+          add=$(cat < "${json_plan}" | jq -rs '.[] | select(.type=="change_summary").changes.add')
+          change=$(cat < "${json_plan}" | jq -rs '.[] | select(.type=="change_summary").changes.change')
+          remove=$(cat < "${json_plan}" | jq -rs '.[] | select(.type=="change_summary").changes.remove')
+
+          if [[ -n "$remove" ]] && [[ "$remove" -gt 0 ]]; then
+              echo "::warning::${msg}"
+          else
+              echo "::notice::${msg}"
+          fi
+
+  terraform_finalize:
+    name: Finalize Terraform
+    runs-on: ${{ fromJSON(inputs.runs_on) }}
+    strategy:
+      fail-fast: false
+      matrix:
+        project: ${{ fromJSON(needs.is_terraform.outputs.projects) }}
+    timeout-minutes: ${{ fromJSON(inputs.jobs_timeout_minutes) }}
+    needs:
+      - is_pr_merged
+      - is_pushed_tag
+      - is_terraform
+    if: |
+      !failure() && !cancelled() &&
+      needs.is_pr_merged.result != needs.is_pushed_tag.result &&
+      needs.is_terraform.outputs.terraform == 'true'
+
+    defaults:
+      run:
+        working-directory: ${{ matrix.project }}
+
+    env:
+      KUBE_CTX: ${{ vars.KUBECTL_CONTEXT }}
+      KUBE_NAMESPACE: ${{ vars.KUBE_NAMESPACE }}
+      LOCK_TIMEOUT: 300s
+
+    steps:
+      - *checkoutVersionedSha
+      - *randomDelay
+      - *configureAWSCredentials
+      - *getAWSCallerIdentity
+      - *updateKubeconfig
+
+      - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2
+        with:
+          terraform_wrapper: false
+          terraform_version: 1.3.9
+
+      - name: Terraform apply
+        env:
+          SECRETS_CONTEXT: ${{ toJson(secrets) }}
+          VARS_CONTEXT: ${{ toJson(vars) }}
+        run: |
+          set -a
+
+          trap 'rm -f .env' EXIT
+
+          to_envs() { jq -r "to_entries[] | \"\(.key)="\'"\(.value)"\'"\""; }
+
+          echo "${SECRETS_CONTEXT}" | to_envs > .env
+          echo "${VARS_CONTEXT}" | to_envs >> .env
+          source .env && rm -f .env
+
+          rc=0
+          terraform plan -lock-timeout=${LOCK_TIMEOUT} -detailed-exitcode || rc=$?
+          if [[ $rc -eq 2 ]]; then
+              terraform apply -lock-timeout=300s -auto-approve
+          elif [[ $rc -eq 0 ]]; then
+              true
+          else
+              false
+          fi
 
   protect_branch:
     name: Protect branch
@@ -3523,6 +3835,7 @@ jobs:
       - cargo_test
       - custom_test
       - cloudformation_test
+      - terraform_test
     if: |
       always() &&
       needs.is_pr_open.result != 'skipped'
@@ -3554,7 +3867,6 @@ jobs:
       - cargo_publish
       - custom_publish
       - custom_always
-      - cloudformation_finalize
       - protect_branch
     if: |
       always() &&
