Make sure protect branch always runs and cannot be skipped
A skipped or cancelled result will not prevent a PR from being
merged.

Change-type: patch
Signed-off-by: Kyle Harding <kyle@balena.io>

diff --git a/flowzone.yml b/flowzone.yml
--- a/flowzone.yml
+++ b/flowzone.yml
@@ -2758,16 +2758,21 @@ jobs:
     timeout-minutes: ${{ fromJSON(inputs.jobs_timeout_minutes) }}
     needs:
       - is_pr_open
+      - npm_test
+      - npm_publish
+      - docker_test
       - docker_publish
       - balena_publish
-      - custom_publish
-      - npm_publish
-      - cargo_publish
-      - github_publish
+      - python_test
       - website_publish
+      - github_publish
+      - cargo_test
+      - cargo_publish
+      - custom_test
+      - custom_publish
       - custom_always
     if: |
-      !failure() && !cancelled() &&
+      always() &&
       needs.is_pr_open.result == 'success' &&
       inputs.protect_branch == true &&
       github.event.pull_request.head.repo.full_name == github.repository &&
@@ -2786,6 +2791,20 @@ jobs:
       - *getGitHubAppInstallationToken
       - *mapGitHubTokens
       - *isDraftPullRequest
+
+      # loop over all needed jobs and fail this job if any of them failed
+      - name: Check needed jobs
+        run: |
+          if [ "${{ contains(needs.*.result, 'failure') }}" = "true" ]
+          then
+            echo "One or more jobs have a status of failure"
+            exit 1
+          fi
+          if [ "${{ contains(needs.*.result, 'cancelled') }}" = "true" ]
+          then
+            echo "One or more jobs have a status of cancelled"
+            exit 1
+          fi
 
       - name: Get protection rules
         id: get_protection_rules
