Use the runner OS release version in agent tools cache key
This prevents runners of the same OS and Arch but different major
releases from sharing a cache.

For example, setup-python binaries are specific to Ubuntu 22.04 vs 24.04.

Change-type: patch
Signed-off-by: Kyle Harding <kyle@balena.io>

diff --git a/.github/actions/test/action.yml b/.github/actions/test/action.yml
--- a/.github/actions/test/action.yml
+++ b/.github/actions/test/action.yml
@@ -50,6 +50,32 @@ runs:
         git submodule
         git --no-pager tag --list --sort=-version:refname "v*.*.*" --merged
 
+    - name: Get runner OS release
+      shell: bash
+      run: |
+        set -ex
+        case "${{ runner.OS }}" in
+          Linux)
+            RUNNER_RELEASE=$(lsb_release --release --short)
+            ;;
+          macOS)
+            RUNNER_RELEASE=$(sw_vers --productVersion)
+            ;;
+          Windows)
+            RUNNER_RELEASE=$(pwsh.exe -Command "(Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion').DisplayVersion")
+            ;;
+          *)
+            echo ":error:Unsupported OS: ${{ runner.OS }}"
+            ;;
+        esac
+
+        if [[ -z "${RUNNER_RELEASE:-}" ]]; then
+          echo ":error:Failed to get runner OS release"
+          exit 1
+        fi
+
+        echo "RUNNER_RELEASE=${RUNNER_RELEASE}" >>${GITHUB_ENV}
+
     # https://github.com/actions/runner-images/discussions/7191#discussioncomment-8351370
     # https://github.com/reactivecircus/android-emulator-runner?tab=readme-ov-file#running-hardware-accelerated-emulators-on-linux-runners
     # https://github.com/ankidroid/Anki-Android/commit/3a5ecaa9837691817022d11b0dbe383b8e82d9fe
diff --git a/.github/workflows/flowzone.yml b/.github/workflows/flowzone.yml
--- a/.github/workflows/flowzone.yml
+++ b/.github/workflows/flowzone.yml
@@ -1210,15 +1210,39 @@ jobs:
           SHA: ${{ needs.versioned_source.outputs.tag_sha }}
         run: |
           git update-ref "refs/tags/${TAG}" "${SHA}"
+      - name: Get runner OS release
+        if: runner.environment == 'self-hosted'
+        run: |
+          case "${{ runner.OS }}" in
+            Linux)
+              RUNNER_RELEASE=$(lsb_release --release --short)
+              ;;
+            macOS)
+              RUNNER_RELEASE=$(sw_vers --productVersion)
+              ;;
+            Windows)
+              RUNNER_RELEASE=$(pwsh.exe -Command "(Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion').DisplayVersion")
+              ;;
+            *)
+              echo ":error:Unsupported OS: ${{ runner.OS }}"
+              ;;
+          esac
+
+          if [[ -z "${RUNNER_RELEASE:-}" ]]; then
+            echo ":error:Failed to get runner OS release"
+            exit 1
+          fi
+
+          echo "RUNNER_RELEASE=${RUNNER_RELEASE}" >>${GITHUB_ENV}
       - name: Cache agent tools
         id: cache-agent-tools
         if: runner.environment == 'self-hosted'
         uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
         with:
           path: ${{ runner.tool_cache }}/*
-          key: ${{ runner.os }}-${{ runner.arch }}-agent-tools-${{ github.ref_name }}
+          key: ${{ runner.os }}-${{ env.RUNNER_RELEASE }}-${{ runner.arch }}-agent-tools-${{ github.ref_name }}
           restore-keys: |
-            ${{ runner.os }}-${{ runner.arch }}-agent-tools-
+            ${{ runner.os }}-${{ env.RUNNER_RELEASE }}-${{ runner.arch }}-agent-tools-
       - name: Setup python
         id: setup-python
         uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548
@@ -1761,15 +1785,39 @@ jobs:
             echo "enabled=false" >> "${GITHUB_OUTPUT}"
             echo "pypi_publish=false" >> "${GITHUB_OUTPUT}"
           fi
+      - name: Get runner OS release
+        if: runner.environment == 'self-hosted'
+        run: |
+          case "${{ runner.OS }}" in
+            Linux)
+              RUNNER_RELEASE=$(lsb_release --release --short)
+              ;;
+            macOS)
+              RUNNER_RELEASE=$(sw_vers --productVersion)
+              ;;
+            Windows)
+              RUNNER_RELEASE=$(pwsh.exe -Command "(Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion').DisplayVersion")
+              ;;
+            *)
+              echo ":error:Unsupported OS: ${{ runner.OS }}"
+              ;;
+          esac
+
+          if [[ -z "${RUNNER_RELEASE:-}" ]]; then
+            echo ":error:Failed to get runner OS release"
+            exit 1
+          fi
+
+          echo "RUNNER_RELEASE=${RUNNER_RELEASE}" >>${GITHUB_ENV}
       - name: Cache agent tools
         id: cache-agent-tools
         if: runner.environment == 'self-hosted'
         uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
         with:
           path: ${{ runner.tool_cache }}/*
-          key: ${{ runner.os }}-${{ runner.arch }}-agent-tools-${{ github.ref_name }}
+          key: ${{ runner.os }}-${{ env.RUNNER_RELEASE }}-${{ runner.arch }}-agent-tools-${{ github.ref_name }}
           restore-keys: |
-            ${{ runner.os }}-${{ runner.arch }}-agent-tools-
+            ${{ runner.os }}-${{ env.RUNNER_RELEASE }}-${{ runner.arch }}-agent-tools-
       - name: Setup python
         id: setup-python
         uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548
@@ -3670,15 +3718,39 @@ jobs:
           SHA: ${{ needs.versioned_source.outputs.tag_sha }}
         run: |
           git update-ref "refs/tags/${TAG}" "${SHA}"
+      - name: Get runner OS release
+        if: runner.environment == 'self-hosted'
+        run: |
+          case "${{ runner.OS }}" in
+            Linux)
+              RUNNER_RELEASE=$(lsb_release --release --short)
+              ;;
+            macOS)
+              RUNNER_RELEASE=$(sw_vers --productVersion)
+              ;;
+            Windows)
+              RUNNER_RELEASE=$(pwsh.exe -Command "(Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion').DisplayVersion")
+              ;;
+            *)
+              echo ":error:Unsupported OS: ${{ runner.OS }}"
+              ;;
+          esac
+
+          if [[ -z "${RUNNER_RELEASE:-}" ]]; then
+            echo ":error:Failed to get runner OS release"
+            exit 1
+          fi
+
+          echo "RUNNER_RELEASE=${RUNNER_RELEASE}" >>${GITHUB_ENV}
       - name: Cache agent tools
         id: cache-agent-tools
         if: runner.environment == 'self-hosted'
         uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
         with:
           path: ${{ runner.tool_cache }}/*
-          key: ${{ runner.os }}-${{ runner.arch }}-agent-tools-${{ github.ref_name }}
+          key: ${{ runner.os }}-${{ env.RUNNER_RELEASE }}-${{ runner.arch }}-agent-tools-${{ github.ref_name }}
           restore-keys: |
-            ${{ runner.os }}-${{ runner.arch }}-agent-tools-
+            ${{ runner.os }}-${{ env.RUNNER_RELEASE }}-${{ runner.arch }}-agent-tools-
       - name: Setup python
         id: setup-python
         uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548
@@ -3787,15 +3859,39 @@ jobs:
           SHA: ${{ needs.versioned_source.outputs.tag_sha }}
         run: |
           git update-ref "refs/tags/${TAG}" "${SHA}"
+      - name: Get runner OS release
+        if: runner.environment == 'self-hosted'
+        run: |
+          case "${{ runner.OS }}" in
+            Linux)
+              RUNNER_RELEASE=$(lsb_release --release --short)
+              ;;
+            macOS)
+              RUNNER_RELEASE=$(sw_vers --productVersion)
+              ;;
+            Windows)
+              RUNNER_RELEASE=$(pwsh.exe -Command "(Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion').DisplayVersion")
+              ;;
+            *)
+              echo ":error:Unsupported OS: ${{ runner.OS }}"
+              ;;
+          esac
+
+          if [[ -z "${RUNNER_RELEASE:-}" ]]; then
+            echo ":error:Failed to get runner OS release"
+            exit 1
+          fi
+
+          echo "RUNNER_RELEASE=${RUNNER_RELEASE}" >>${GITHUB_ENV}
       - name: Cache agent tools
         id: cache-agent-tools
         if: runner.environment == 'self-hosted'
         uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
         with:
           path: ${{ runner.tool_cache }}/*
-          key: ${{ runner.os }}-${{ runner.arch }}-agent-tools-${{ github.ref_name }}
+          key: ${{ runner.os }}-${{ env.RUNNER_RELEASE }}-${{ runner.arch }}-agent-tools-${{ github.ref_name }}
           restore-keys: |
-            ${{ runner.os }}-${{ runner.arch }}-agent-tools-
+            ${{ runner.os }}-${{ env.RUNNER_RELEASE }}-${{ runner.arch }}-agent-tools-
       - name: Setup python
         id: setup-python
         uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548
@@ -3900,15 +3996,39 @@ jobs:
           SHA: ${{ needs.versioned_source.outputs.tag_sha }}
         run: |
           git update-ref "refs/tags/${TAG}" "${SHA}"
+      - name: Get runner OS release
+        if: runner.environment == 'self-hosted'
+        run: |
+          case "${{ runner.OS }}" in
+            Linux)
+              RUNNER_RELEASE=$(lsb_release --release --short)
+              ;;
+            macOS)
+              RUNNER_RELEASE=$(sw_vers --productVersion)
+              ;;
+            Windows)
+              RUNNER_RELEASE=$(pwsh.exe -Command "(Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion').DisplayVersion")
+              ;;
+            *)
+              echo ":error:Unsupported OS: ${{ runner.OS }}"
+              ;;
+          esac
+
+          if [[ -z "${RUNNER_RELEASE:-}" ]]; then
+            echo ":error:Failed to get runner OS release"
+            exit 1
+          fi
+
+          echo "RUNNER_RELEASE=${RUNNER_RELEASE}" >>${GITHUB_ENV}
       - name: Cache agent tools
         id: cache-agent-tools
         if: runner.environment == 'self-hosted'
         uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
         with:
           path: ${{ runner.tool_cache }}/*
-          key: ${{ runner.os }}-${{ runner.arch }}-agent-tools-${{ github.ref_name }}
+          key: ${{ runner.os }}-${{ env.RUNNER_RELEASE }}-${{ runner.arch }}-agent-tools-${{ github.ref_name }}
           restore-keys: |
-            ${{ runner.os }}-${{ runner.arch }}-agent-tools-
+            ${{ runner.os }}-${{ env.RUNNER_RELEASE }}-${{ runner.arch }}-agent-tools-
       - name: Setup python
         id: setup-python
         uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548
@@ -3999,15 +4119,39 @@ jobs:
           SHA: ${{ needs.versioned_source.outputs.tag_sha }}
         run: |
           git update-ref "refs/tags/${TAG}" "${SHA}"
+      - name: Get runner OS release
+        if: runner.environment == 'self-hosted'
+        run: |
+          case "${{ runner.OS }}" in
+            Linux)
+              RUNNER_RELEASE=$(lsb_release --release --short)
+              ;;
+            macOS)
+              RUNNER_RELEASE=$(sw_vers --productVersion)
+              ;;
+            Windows)
+              RUNNER_RELEASE=$(pwsh.exe -Command "(Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion').DisplayVersion")
+              ;;
+            *)
+              echo ":error:Unsupported OS: ${{ runner.OS }}"
+              ;;
+          esac
+
+          if [[ -z "${RUNNER_RELEASE:-}" ]]; then
+            echo ":error:Failed to get runner OS release"
+            exit 1
+          fi
+
+          echo "RUNNER_RELEASE=${RUNNER_RELEASE}" >>${GITHUB_ENV}
       - name: Cache agent tools
         id: cache-agent-tools
         if: runner.environment == 'self-hosted'
         uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
         with:
           path: ${{ runner.tool_cache }}/*
-          key: ${{ runner.os }}-${{ runner.arch }}-agent-tools-${{ github.ref_name }}
+          key: ${{ runner.os }}-${{ env.RUNNER_RELEASE }}-${{ runner.arch }}-agent-tools-${{ github.ref_name }}
           restore-keys: |
-            ${{ runner.os }}-${{ runner.arch }}-agent-tools-
+            ${{ runner.os }}-${{ env.RUNNER_RELEASE }}-${{ runner.arch }}-agent-tools-
       - name: Setup python
         id: setup-python
         uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548
@@ -5424,15 +5568,39 @@ jobs:
           fi
 
           echo "caps=${caps}" >> "${GITHUB_OUTPUT}"
+      - name: Get runner OS release
+        if: runner.environment == 'self-hosted'
+        run: |
+          case "${{ runner.OS }}" in
+            Linux)
+              RUNNER_RELEASE=$(lsb_release --release --short)
+              ;;
+            macOS)
+              RUNNER_RELEASE=$(sw_vers --productVersion)
+              ;;
+            Windows)
+              RUNNER_RELEASE=$(pwsh.exe -Command "(Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion').DisplayVersion")
+              ;;
+            *)
+              echo ":error:Unsupported OS: ${{ runner.OS }}"
+              ;;
+          esac
+
+          if [[ -z "${RUNNER_RELEASE:-}" ]]; then
+            echo ":error:Failed to get runner OS release"
+            exit 1
+          fi
+
+          echo "RUNNER_RELEASE=${RUNNER_RELEASE}" >>${GITHUB_ENV}
       - name: Cache agent tools
         id: cache-agent-tools
         if: runner.environment == 'self-hosted'
         uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
         with:
           path: ${{ runner.tool_cache }}/*
-          key: ${{ runner.os }}-${{ runner.arch }}-agent-tools-${{ github.ref_name }}
+          key: ${{ runner.os }}-${{ env.RUNNER_RELEASE }}-${{ runner.arch }}-agent-tools-${{ github.ref_name }}
           restore-keys: |
-            ${{ runner.os }}-${{ runner.arch }}-agent-tools-
+            ${{ runner.os }}-${{ env.RUNNER_RELEASE }}-${{ runner.arch }}-agent-tools-
       - name: Setup python
         id: setup-python
         uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548
diff --git a/flowzone.yml b/flowzone.yml
--- a/flowzone.yml
+++ b/flowzone.yml
@@ -622,10 +622,40 @@
     with:
       version: "2.15.43"
 
+  # Export runner OS release version for use by cache actions
+  - &getRunnerRelease
+    name: Get runner OS release
+    if: runner.environment == 'self-hosted'
+    run: |
+      case "${{ runner.OS }}" in
+        Linux)
+          RUNNER_RELEASE=$(lsb_release --release --short)
+          ;;
+        macOS)
+          RUNNER_RELEASE=$(sw_vers --productVersion)
+          ;;
+        Windows)
+          RUNNER_RELEASE=$(pwsh.exe -Command "(Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion').DisplayVersion")
+          ;;
+        *)
+          echo ":error:Unsupported OS: ${{ runner.OS }}"
+          ;;
+      esac
+
+      if [[ -z "${RUNNER_RELEASE:-}" ]]; then
+        echo ":error:Failed to get runner OS release"
+        exit 1
+      fi
+
+      echo "RUNNER_RELEASE=${RUNNER_RELEASE}" >>${GITHUB_ENV}
+
   # Self-hosted runners don't have a populated tool cache so we should cache anything that
   # is successfully downloaded so it can be used by the next job/run.
   # Caches can be restored from the default branch or the current branch.
   # https://docs.github.com/en/actions/reference/workflows-and-actions/dependency-caching
+  # Use the runner OS release version to prevent runners of the same OS and Arch from sharing a runner tools cache
+  # if their distro release differs.
+  # For example, setup-python binaries are specific to Ubuntu 22.04 vs 24.04.
   - &cacheAgentTools # https://github.com/actions/cache
     name: Cache agent tools
     id: cache-agent-tools
@@ -633,9 +663,9 @@
     uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
     with:
       path: ${{ runner.tool_cache }}/*
-      key: ${{ runner.os }}-${{ runner.arch }}-agent-tools-${{ github.ref_name }}
+      key: ${{ runner.os }}-${{ env.RUNNER_RELEASE }}-${{ runner.arch }}-agent-tools-${{ github.ref_name }}
       restore-keys: |
-        ${{ runner.os }}-${{ runner.arch }}-agent-tools-
+        ${{ runner.os }}-${{ env.RUNNER_RELEASE }}-${{ runner.arch }}-agent-tools-
 
   - &waitForCloudFormation
     name: Wait for resources
@@ -1905,6 +1935,7 @@ jobs:
       - *checkoutVersionedCommit
       - *checkoutSubmodules
       - *updateVersionedTagRef
+      - *getRunnerRelease
       - *cacheAgentTools
       - <<: *setupPython
         with:
@@ -2417,6 +2448,7 @@ jobs:
             echo "pypi_publish=false" >> "${GITHUB_OUTPUT}"
           fi
 
+      - *getRunnerRelease
       - *cacheAgentTools
       - <<: *setupPython
         if: steps.python_poetry.outputs.enabled == 'true'
@@ -3674,7 +3706,7 @@ jobs:
       - *checkoutVersionedCommit
       - *checkoutSubmodules
       - *updateVersionedTagRef
-
+      - *getRunnerRelease
       - *cacheAgentTools
       - <<: *setupPython
         with:
@@ -3751,7 +3783,7 @@ jobs:
       - *checkoutVersionedCommit
       - *checkoutSubmodules
       - *updateVersionedTagRef
-
+      - *getRunnerRelease
       - *cacheAgentTools
       - *setupPython
 
@@ -3809,7 +3841,7 @@ jobs:
       - *checkoutVersionedCommit
       - *checkoutSubmodules
       - *updateVersionedTagRef
-
+      - *getRunnerRelease
       - *cacheAgentTools
       - *setupPython
       - *setupPoetry
@@ -3850,7 +3882,7 @@ jobs:
       - *checkoutVersionedCommit
       - *checkoutSubmodules
       - *updateVersionedTagRef
-
+      - *getRunnerRelease
       - *cacheAgentTools
       - *setupPython
       - *setupPoetry
@@ -4724,6 +4756,7 @@ jobs:
 
           echo "caps=${caps}" >> "${GITHUB_OUTPUT}"
 
+      - *getRunnerRelease
       - *cacheAgentTools
       - <<: *setupPython
         with:
