Add composite workflow support
Change-type: patch
Signed-off-by: Kyle Harding <kyle@balena.io>

diff --git a/.github/workflows/flowzone.yml b/.github/workflows/flowzone.yml
--- a/.github/workflows/flowzone.yml
+++ b/.github/workflows/flowzone.yml
@@ -209,6 +209,10 @@ jobs:
       docker: ${{ steps.docker.outputs.enabled }}
       balena: ${{ steps.balena.outputs.enabled }}
 
+      custom_draft: ${{ steps.custom.outputs.draft }}
+      custom_finalize: ${{ steps.custom.outputs.finalize }}
+      custom_test: ${{ steps.custom.outputs.test }}
+
     steps:
       - name: Download source artifact
         uses: actions/download-artifact@v3
@@ -252,30 +256,64 @@ jobs:
             echo ::set-output name=enabled::"false"
           fi
 
+      - name: Check for custom jobs
+        id: custom
+        working-directory: .
+        run: |
+          test -d .github/flowzone/draft && echo "::set-output name=draft::true"
+          test -d .github/flowzone/finalize && echo "::set-output name=finalize::true"
+          test -d .github/flowzone/test && echo "::set-output name=test::true"
+
   # this job will always run so it can be used as a branch rule
-  check_results:
-    name: Check results
+  # and other stages can depend on it to control job order
+  all_drafts:
+    name: Draft checkpoint
     runs-on: ubuntu-latest
-    # depend on all the jobs to check overall success
+    needs:
+      [
+        context_check,
+        project_types,
+        package_source,
+        docker_draft,
+        npm_draft,
+        custom_draft,
+        balena_push,
+      ]
+    # always run to avoid being skipped when dependencies are skipped
+    if: always()
+
+    steps:
+      # loop over all needed jobs and fail this job if any of them failed
+      - name: Check results
+        run: |
+          for result in $(echo '${{ toJSON(needs.*.result) }}' | jq -cr '.[]')
+          do
+            test "${result}" = "success" && continue
+            test "${result}" = "skipped" && continue
+            echo "Exiting with overall result ${result}"
+            exit 1
+          done
+
+  # this job will always run so it can be used as a branch rule
+  # and other stages can depend on it to control job order
+  all_tests:
+    name: Test checkpoint
+    runs-on: ubuntu-latest
     needs:
       [
         context_check,
         project_types,
         package_source,
         docker_test,
-        docker_draft,
-        docker_finalize,
         npm_test,
-        npm_draft,
-        npm_finalize,
-        balena_push,
+        custom_test,
       ]
-    # always run to avoid being skipped when dependencies fail
+    # always run to avoid being skipped when dependencies are skipped
     if: always()
 
     steps:
       # loop over all needed jobs and fail this job if any of them failed
-      - name: Check overall result
+      - name: Check results
         run: |
           for result in $(echo '${{ toJSON(needs.*.result) }}' | jq -cr '.[]')
           do
@@ -288,12 +326,13 @@ jobs:
   protect_branch:
     name: Protect branch
     runs-on: ubuntu-latest
-    needs: [context_check, check_results]
+    needs: [context_check, all_drafts, all_tests]
     if: |
       always() &&
       inputs.protect_branch == true &&
       github.event_name == 'pull_request' &&
-      needs.check_results.result == 'success'
+      needs.all_drafts.result == 'success' &&
+      needs.all_tests.result == 'success'
 
     outputs:
       result: ${{ steps.apply_branch_protection_rules.outputs.result }}
@@ -317,7 +356,8 @@ jobs:
               "strict": true,
               "contexts": [
                 "Flowzone / Check context",
-                "Flowzone / Check results",
+                "Flowzone / Test checkpoint",
+                "Flowzone / Draft checkpoint",
                 "Flowzone / Protect branch",
                 ${{ inputs.required_status_checks }}
               ]
@@ -489,8 +529,7 @@ jobs:
   npm_draft:
     name: Draft npm
     runs-on: ubuntu-latest
-    needs:
-      [context_check, project_types, package_source, npm_test]
+    needs: [context_check, project_types, package_source, all_tests]
     if: |
       inputs.npm_registry != '' &&
       needs.project_types.outputs.npm_private != 'true'
@@ -676,13 +715,7 @@ jobs:
   docker_draft:
     name: Draft docker
     runs-on: ubuntu-latest
-    needs:
-      [
-        context_check,
-        project_types,
-        package_source,
-        docker_test,
-      ]
+    needs: [context_check, project_types, package_source, all_tests]
     if: |
       inputs.docker_images != ''
 
@@ -873,7 +906,7 @@ jobs:
   balena_push:
     name: Push balena
     runs-on: ubuntu-latest
-    needs: [context_check, project_types, package_source]
+    needs: [context_check, project_types, package_source, all_tests]
     if: needs.project_types.outputs.balena == 'true'
 
     strategy:
@@ -902,3 +935,93 @@ jobs:
           fleet: ${{ matrix.slug }}
           versionbot: false # disable the included versionbot branch checkout
           source: ${{ inputs.working_directory }}
+
+  ###################################################
+  ## custom
+  ###################################################
+
+  custom_test:
+    name: Test custom
+    runs-on: ubuntu-latest
+    needs: [context_check, project_types, package_source]
+    if: |
+      needs.project_types.outputs.custom_test == 'true' &&
+      github.event_name == 'pull_request' &&
+      github.event.pull_request.merged == false
+
+    defaults:
+      run:
+        working-directory: ${{ inputs.working_directory }}
+        shell: ${{ needs.context_check.outputs.shell }}
+
+    steps:
+      - name: Download source artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: source-${{ github.event.pull_request.head.sha }}
+
+      - name: Extract source artifact
+        working-directory: .
+        run: tar -xvf source.tar
+
+      - name: Call custom action
+        uses: ./.github/flowzone/test
+        with:
+          who-to-greet: "Mona the Octocat"
+
+  custom_draft:
+    name: Draft custom
+    runs-on: ubuntu-latest
+    needs: [context_check, project_types, package_source, all_tests]
+    if: |
+      needs.project_types.outputs.custom_draft == 'true' &&
+      github.event_name == 'pull_request' &&
+      github.event.pull_request.merged == false
+
+    defaults:
+      run:
+        working-directory: ${{ inputs.working_directory }}
+        shell: ${{ needs.context_check.outputs.shell }}
+
+    steps:
+      - name: Download source artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: source-${{ github.event.pull_request.head.sha }}
+
+      - name: Extract source artifact
+        working-directory: .
+        run: tar -xvf source.tar
+
+      - name: Call custom action
+        uses: ./.github/flowzone/draft
+        with:
+          who-to-greet: "Mona the Octocat"
+
+  custom_finalize:
+    name: Finalize custom
+    runs-on: ubuntu-latest
+    needs: [context_check, project_types, package_source]
+    if: |
+      needs.project_types.outputs.custom_finalize == 'true' &&
+      (github.event_name != 'pull_request' || github.event.pull_request.merged == true)
+
+    defaults:
+      run:
+        working-directory: ${{ inputs.working_directory }}
+        shell: ${{ needs.context_check.outputs.shell }}
+
+    steps:
+      - name: Download source artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: source-${{ github.event.pull_request.head.sha }}
+
+      - name: Extract source artifact
+        working-directory: .
+        run: tar -xvf source.tar
+
+      - name: Call custom action
+        uses: ./.github/flowzone/finalize
+        with:
+          who-to-greet: "Mona the Octocat"
