Correct external contribution restrictions
Change-type: patch
Signed-off-by: Kyle Harding <kyle@balena.io>

diff --git a/.github/workflows/flowzone.yml b/.github/workflows/flowzone.yml
--- a/.github/workflows/flowzone.yml
+++ b/.github/workflows/flowzone.yml
@@ -298,13 +298,33 @@ jobs:
     timeout-minutes: ${{ fromJSON(inputs.jobs_timeout_minutes) }}
     if: |
       (
-        github.event_name == 'pull_request' ||
-        github.event_name == 'pull_request_target'
+        (
+          github.event_name == 'pull_request' &&
+          github.event.pull_request.head.repo.full_name == github.repository
+        ) || (
+          github.event_name == 'pull_request_target' &&
+          github.event.pull_request.head.repo.full_name != github.repository
+        )
       ) && (
         github.event.action == 'opened' ||
         github.event.action == 'synchronize'
       )
     steps:
+      - name: Reject external workflow changes
+        if: github.event.pull_request.head.repo.full_name != github.repository
+        env:
+          GH_DEBUG: "true"
+          GH_PAGER: cat
+          GH_PROMPT_DISABLED: "true"
+          GH_REPO: ${{ github.repository }}
+          GH_TOKEN: ${{ steps.gh_token.outputs.token || secrets.FLOWZONE_TOKEN }}
+        run: |
+          if [[ $(gh pr diff ${{ github.event.pull_request.number }} --name-only) =~ ^\.github\/ ]]
+          then
+            echo "::error::Modifications to workflow files are not supported for external contributions. \
+              Please contact a member of the organization for assistance."
+            exit 1
+          fi
       - name: Log GitHub context
         env:
           GITHUB_CONTEXT: ${{ toJSON(github) }}
@@ -315,13 +335,33 @@ jobs:
     timeout-minutes: ${{ fromJSON(inputs.jobs_timeout_minutes) }}
     if: |
       (
-        github.event_name == 'pull_request' ||
-        github.event_name == 'pull_request_target'
+        (
+          github.event_name == 'pull_request' &&
+          github.event.pull_request.head.repo.full_name == github.repository
+        ) || (
+          github.event_name == 'pull_request_target' &&
+          github.event.pull_request.head.repo.full_name != github.repository
+        )
       ) && (
         github.event.action == 'closed' &&
         github.event.pull_request.merged == false
       )
     steps:
+      - name: Reject external workflow changes
+        if: github.event.pull_request.head.repo.full_name != github.repository
+        env:
+          GH_DEBUG: "true"
+          GH_PAGER: cat
+          GH_PROMPT_DISABLED: "true"
+          GH_REPO: ${{ github.repository }}
+          GH_TOKEN: ${{ steps.gh_token.outputs.token || secrets.FLOWZONE_TOKEN }}
+        run: |
+          if [[ $(gh pr diff ${{ github.event.pull_request.number }} --name-only) =~ ^\.github\/ ]]
+          then
+            echo "::error::Modifications to workflow files are not supported for external contributions. \
+              Please contact a member of the organization for assistance."
+            exit 1
+          fi
       - name: Log GitHub context
         env:
           GITHUB_CONTEXT: ${{ toJSON(github) }}
@@ -332,13 +372,33 @@ jobs:
     timeout-minutes: ${{ fromJSON(inputs.jobs_timeout_minutes) }}
     if: |
       (
-        github.event_name == 'pull_request' ||
-        github.event_name == 'pull_request_target'
+        (
+          github.event_name == 'pull_request' &&
+          github.event.pull_request.head.repo.full_name == github.repository
+        ) || (
+          github.event_name == 'pull_request_target' &&
+          github.event.pull_request.head.repo.full_name != github.repository
+        )
       ) && (
         github.event.action == 'closed' &&
         github.event.pull_request.merged == true
       )
     steps:
+      - name: Reject external workflow changes
+        if: github.event.pull_request.head.repo.full_name != github.repository
+        env:
+          GH_DEBUG: "true"
+          GH_PAGER: cat
+          GH_PROMPT_DISABLED: "true"
+          GH_REPO: ${{ github.repository }}
+          GH_TOKEN: ${{ steps.gh_token.outputs.token || secrets.FLOWZONE_TOKEN }}
+        run: |
+          if [[ $(gh pr diff ${{ github.event.pull_request.number }} --name-only) =~ ^\.github\/ ]]
+          then
+            echo "::error::Modifications to workflow files are not supported for external contributions. \
+              Please contact a member of the organization for assistance."
+            exit 1
+          fi
       - name: Log GitHub context
         env:
           GITHUB_CONTEXT: ${{ toJSON(github) }}
@@ -504,35 +564,6 @@ jobs:
           fetch-depth: 0
           submodules: recursive
           token: ${{ steps.gh_token.outputs.token || secrets.FLOWZONE_TOKEN }}
-      - name: Check external contributor limitations
-        if: github.event.pull_request.head.repo.full_name != github.repository
-        env:
-          GH_DEBUG: "true"
-          GH_PAGER: cat
-          GH_PROMPT_DISABLED: "true"
-          GH_REPO: ${{ github.repository }}
-          GH_TOKEN: ${{ steps.gh_token.outputs.token || secrets.FLOWZONE_TOKEN }}
-        run: |
-          if [ -n "${{ secrets.COMPOSE_VARS }}" ]
-          then
-            echo "::notice::COMPOSE_VARS secrets are not currently supported for external contributions. \
-              Please contact a member of the organization for assistance."
-            exit 1
-          fi
-
-          if [[ $(gh pr diff ${{ github.event.pull_request.number }} --name-only) =~ ^\.github\/ ]]
-          then
-            echo "::notice::Modifications to workflow files are not supported for external contributions. \
-              Please contact a member of the organization for assistance."
-            exit 1
-          fi
-
-          if [ "${{ inputs.restrict_custom_actions }}" == "true" ]
-          then
-            echo "::notice::Custom actions are disabled for external contributors and will be skipped. \
-              Please contact a member of the organization for assistance."
-            exit 0
-          fi
       - name: Reject merge commits
         run: |
           if [ "$(git cat-file -p ${{ github.event.pull_request.head.sha || github.event.head_commit.id }} | grep '^parent ' | wc -l)" -gt 1 ]
@@ -1550,13 +1581,11 @@ jobs:
       - name: Save image to file
         run: |
           docker save ${{ fromJSON(steps.meta.outputs.json).tags[0] }} > ${{ env.IMAGE_TAR }}
-      - name: Run docker compose tests
-        if: needs.docker_check.outputs.docker_compose_tests == 'true'
-        shell: bash
+      - name: Inject COMPOSE_VARS
+        if: github.event.pull_request.head.repo.full_name == github.repository
         env:
           COMPOSE_VARS: ${{ secrets.COMPOSE_VARS }}
-          DOCKER_BUILDKIT: "1"
-          COMPOSE_FILE: docker-compose.override.yml
+        shell: bash
         run: |
           if [ -n "${COMPOSE_VARS}" ]
           then
@@ -1568,7 +1597,13 @@ jobs:
               echo "::add-mask::${secret}"
             done < .env
           fi
-
+      - name: Run docker compose tests
+        if: needs.docker_check.outputs.docker_compose_tests == 'true'
+        shell: bash
+        env:
+          DOCKER_BUILDKIT: "1"
+          COMPOSE_FILE: docker-compose.override.yml
+        run: |
           files="
             docker-compose.yml
             docker-compose.yaml
@@ -2371,6 +2406,14 @@ jobs:
         value: ${{ fromJSON(needs.sanitize_inputs.outputs.custom_test_matrix) }}
         os: ${{ fromJSON(inputs.tests_run_on) }}
     steps:
+      - name: Reject external custom actions
+        if: |
+          github.event.pull_request.head.repo.full_name != github.repository &&
+          inputs.restrict_custom_actions == true
+        run: |
+          echo "::error::Custom actions are disabled for external contributors and will be skipped. \
+            Please contact a member of the organization for assistance."
+          exit 1
       - name: Download source artifact
         uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
         with:
@@ -2411,6 +2454,14 @@ jobs:
         value: ${{ fromJSON(needs.sanitize_inputs.outputs.custom_publish_matrix) }}
         os: ${{ fromJSON(inputs.tests_run_on) }}
     steps:
+      - name: Reject external custom actions
+        if: |
+          github.event.pull_request.head.repo.full_name != github.repository &&
+          inputs.restrict_custom_actions == true
+        run: |
+          echo "::error::Custom actions are disabled for external contributors and will be skipped. \
+            Please contact a member of the organization for assistance."
+          exit 1
       - name: Download source artifact
         uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
         with:
@@ -2447,6 +2498,14 @@ jobs:
         value: ${{ fromJSON(needs.sanitize_inputs.outputs.custom_finalize_matrix) }}
         os: ${{ fromJSON(inputs.tests_run_on) }}
     steps:
+      - name: Reject external custom actions
+        if: |
+          github.event.pull_request.head.repo.full_name != github.repository &&
+          inputs.restrict_custom_actions == true
+        run: |
+          echo "::error::Custom actions are disabled for external contributors and will be skipped. \
+            Please contact a member of the organization for assistance."
+          exit 1
       - name: Download source artifact
         uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
         with:
@@ -2480,6 +2539,14 @@ jobs:
       needs.is_pr_closed.result == 'success' &&
       needs.custom_check.outputs.custom_clean == 'true'
     steps:
+      - name: Reject external custom actions
+        if: |
+          github.event.pull_request.head.repo.full_name != github.repository &&
+          inputs.restrict_custom_actions == true
+        run: |
+          echo "::error::Custom actions are disabled for external contributors and will be skipped. \
+            Please contact a member of the organization for assistance."
+          exit 1
       - name: Download source artifact
         uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
         with:
@@ -2511,6 +2578,14 @@ jobs:
       always() &&
       needs.custom_check.outputs.custom_always == 'true'
     steps:
+      - name: Reject external custom actions
+        if: |
+          github.event.pull_request.head.repo.full_name != github.repository &&
+          inputs.restrict_custom_actions == true
+        run: |
+          echo "::error::Custom actions are disabled for external contributors and will be skipped. \
+            Please contact a member of the organization for assistance."
+          exit 1
       - name: Download source artifact
         uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
         with:
diff --git a/flowzone.yml b/flowzone.yml
--- a/flowzone.yml
+++ b/flowzone.yml
@@ -85,6 +85,9 @@
   - &ifInternalPullRequest
     if: github.event.pull_request.head.repo.full_name == github.repository
 
+  - &ifExternalPullRequest
+    if: github.event.pull_request.head.repo.full_name != github.repository
+
   - &ifPrivateRepository
     if: github.event.repository.private
 
@@ -126,6 +129,29 @@
     GH_PROMPT_DISABLED: "true"
     GH_REPO: "${{ github.repository }}"
     GH_TOKEN: "${{ steps.gh_token.outputs.token || secrets.FLOWZONE_TOKEN }}"
+
+  - &rejectExternalWorkflowChanges
+    name: Reject external workflow changes
+    <<: *ifExternalPullRequest
+    env:
+      <<: *gitHubCliEnvironment
+    run: |
+      if [[ $(gh pr diff ${{ github.event.pull_request.number }} --name-only) =~ ^\.github\/ ]]
+      then
+        echo "::error::Modifications to workflow files are not supported for external contributions. \
+          Please contact a member of the organization for assistance."
+        exit 1
+      fi
+
+  - &rejectExternalCustomActions
+    name: Reject external custom actions
+    if: |
+      github.event.pull_request.head.repo.full_name != github.repository &&
+      inputs.restrict_custom_actions == true
+    run: |
+      echo "::error::Custom actions are disabled for external contributors and will be skipped. \
+        Please contact a member of the organization for assistance."
+      exit 1
 
   - &logGitHubContext
     name: Log GitHub context
@@ -479,13 +505,19 @@ jobs:
     timeout-minutes: ${{ fromJSON(inputs.jobs_timeout_minutes) }}
     if: |
       (
-        github.event_name == 'pull_request' ||
-        github.event_name == 'pull_request_target'
+        (
+          github.event_name == 'pull_request' &&
+          github.event.pull_request.head.repo.full_name == github.repository
+        ) || (
+          github.event_name == 'pull_request_target' &&
+          github.event.pull_request.head.repo.full_name != github.repository
+        )
       ) && (
         github.event.action == 'opened' ||
         github.event.action == 'synchronize'
       )
     steps:
+      - *rejectExternalWorkflowChanges
       - *logGitHubContext
 
   # in our context closed does not include merged
@@ -495,13 +527,19 @@ jobs:
     timeout-minutes: ${{ fromJSON(inputs.jobs_timeout_minutes) }}
     if: |
       (
-        github.event_name == 'pull_request' ||
-        github.event_name == 'pull_request_target'
+        (
+          github.event_name == 'pull_request' &&
+          github.event.pull_request.head.repo.full_name == github.repository
+        ) || (
+          github.event_name == 'pull_request_target' &&
+          github.event.pull_request.head.repo.full_name != github.repository
+        )
       ) && (
         github.event.action == 'closed' &&
         github.event.pull_request.merged == false
       )
     steps:
+      - *rejectExternalWorkflowChanges
       - *logGitHubContext
 
   is_pr_merged:
@@ -510,13 +548,19 @@ jobs:
     timeout-minutes: ${{ fromJSON(inputs.jobs_timeout_minutes) }}
     if: |
       (
-        github.event_name == 'pull_request' ||
-        github.event_name == 'pull_request_target'
+        (
+          github.event_name == 'pull_request' &&
+          github.event.pull_request.head.repo.full_name == github.repository
+        ) || (
+          github.event_name == 'pull_request_target' &&
+          github.event.pull_request.head.repo.full_name != github.repository
+        )
       ) && (
         github.event.action == 'closed' &&
         github.event.pull_request.merged == true
       )
     steps:
+      - *rejectExternalWorkflowChanges
       - *logGitHubContext
 
   is_pushed_tag:
@@ -652,33 +696,6 @@ jobs:
       - *getEphemeralToken
       - *checkoutMergeBranch
       - *checkoutSha
-
-      # reject external contribution workflow in certain conditions to prevent leaking secrets
-      - name: Check external contributor limitations
-        if: github.event.pull_request.head.repo.full_name != github.repository
-        env:
-          <<: *gitHubCliEnvironment
-        run: |
-          if [ -n "${{ secrets.COMPOSE_VARS }}" ]
-          then
-            echo "::notice::COMPOSE_VARS secrets are not currently supported for external contributions. \
-              Please contact a member of the organization for assistance."
-            exit 1
-          fi
-
-          if [[ $(gh pr diff ${{ github.event.pull_request.number }} --name-only) =~ ^\.github\/ ]]
-          then
-            echo "::notice::Modifications to workflow files are not supported for external contributions. \
-              Please contact a member of the organization for assistance."
-            exit 1
-          fi
-
-          if [ "${{ inputs.restrict_custom_actions }}" == "true" ]
-          then
-            echo "::notice::Custom actions are disabled for external contributors and will be skipped. \
-              Please contact a member of the organization for assistance."
-            exit 0
-          fi
 
       # fail on merge commits (ones with more than one parent)
       - name: Reject merge commits
@@ -1704,15 +1721,12 @@ jobs:
         run: |
           docker save ${{ fromJSON(steps.meta.outputs.json).tags[0] }} > ${{ env.IMAGE_TAR }}
 
-      # run docker compose tests and print the logs from all services
-      - name: Run docker compose tests
-        if: needs.docker_check.outputs.docker_compose_tests == 'true'
-        # do not use shell tracing to avoid leaking secrets
-        shell: bash
+      - name: Inject COMPOSE_VARS
+        <<: *ifInternalPullRequest
         env:
           COMPOSE_VARS: ${{ secrets.COMPOSE_VARS }}
-          DOCKER_BUILDKIT: "1"
-          COMPOSE_FILE: docker-compose.override.yml
+        # do not use shell tracing to avoid leaking secrets
+        shell: bash
         run: |
           if [ -n "${COMPOSE_VARS}" ]
           then
@@ -1725,6 +1739,15 @@ jobs:
             done < .env
           fi
 
+      # run docker compose tests and print the logs from all services
+      - name: Run docker compose tests
+        if: needs.docker_check.outputs.docker_compose_tests == 'true'
+        # do not use shell tracing to avoid leaking secrets
+        shell: bash
+        env:
+          DOCKER_BUILDKIT: "1"
+          COMPOSE_FILE: docker-compose.override.yml
+        run: |
           files="
             docker-compose.yml
             docker-compose.yaml
@@ -2443,6 +2466,7 @@ jobs:
         os: ${{ fromJSON(inputs.tests_run_on) }}
 
     steps:
+      - *rejectExternalCustomActions
       - *downloadSourceArtifact
       - *extractSourceArtifact
 
@@ -2481,6 +2505,7 @@ jobs:
         os: ${{ fromJSON(inputs.tests_run_on) }}
 
     steps:
+      - *rejectExternalCustomActions
       - *downloadSourceArtifact
       - *extractSourceArtifact
 
@@ -2515,6 +2540,7 @@ jobs:
         os: ${{ fromJSON(inputs.tests_run_on) }}
 
     steps:
+      - *rejectExternalCustomActions
       - *downloadSourceArtifact
       - *extractSourceArtifact
 
@@ -2545,6 +2571,7 @@ jobs:
       needs.custom_check.outputs.custom_clean == 'true'
 
     steps:
+      - *rejectExternalCustomActions
       - *downloadSourceArtifact
       - *extractSourceArtifact
 
@@ -2572,6 +2599,7 @@ jobs:
       needs.custom_check.outputs.custom_always == 'true'
 
     steps:
+      - *rejectExternalCustomActions
       - *downloadSourceArtifact
       - *extractSourceArtifact
 
