use file_list instead

diff --git a/.github/workflows/flowzone.yml b/.github/workflows/flowzone.yml
--- a/.github/workflows/flowzone.yml
+++ b/.github/workflows/flowzone.yml
@@ -1342,22 +1342,11 @@ jobs:
           token: ${{ github.token }}
           ref: ${{ github.event.pull_request.head.sha || github.sha }}
       - name: Check for .dockerignore
-        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
-        env:
-          WORKDIR: ${{ inputs.working_directory }}
-        with:
-          script: |
-            const fs = require('fs');
-            fs.readFile(`${process.env.WORKDIR}/.dockerignore`, 'utf8', (err, data) => {
-              if (err) {
-                console.error('::error:: Docker builds require .dockerignore file.');
-                process.exit(1);
-              } else {
-                if (!data.split('\n').includes('.git')) {
-                  console.warn('::warning:: .dockerignore should exclude .git directory/folder for security reasons.');
-                }
-              }
-            });
+        if: |
+          !contains(needs.file_list.outputs.workdir, '.dockerignore')
+        run: |
+          echo "::error:: Docker builds require .dockerignore file."
+          exit 1
       - name: Setup buildx
         id: setup_buildx
         uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca
diff --git a/flowzone.yml b/flowzone.yml
--- a/flowzone.yml
+++ b/flowzone.yml
@@ -2093,22 +2093,11 @@ jobs:
 
       # enforce .dockerignore requirement and warn (for now) if .git isn't excluded
       - name: Check for .dockerignore
-        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
-        env:
-          WORKDIR: ${{ inputs.working_directory }}
-        with:
-          script: |
-            const fs = require('fs');
-            fs.readFile(`${process.env.WORKDIR}/.dockerignore`, 'utf8', (err, data) => {
-              if (err) {
-                console.error('::error:: Docker builds require .dockerignore file.');
-                process.exit(1);
-              } else {
-                if (!data.split('\n').includes('.git')) {
-                  console.warn('::warning:: .dockerignore should exclude .git directory/folder for security reasons.');
-                }
-              }
-            });
+        if: |
+          !contains(needs.file_list.outputs.workdir, '.dockerignore')
+        run: |
+          echo "::error:: Docker builds require .dockerignore file."
+          exit 1
 
       - <<: *setupBuildx
         env:
