Add boolean trigger jobs
Change-type: minor
Signed-off-by: Kyle Harding <kyle@balena.io>

diff --git a/.github/workflows/flowzone.yml b/.github/workflows/flowzone.yml
--- a/.github/workflows/flowzone.yml
+++ b/.github/workflows/flowzone.yml
@@ -261,18 +261,116 @@ env:
   NPM_REGISTRY: registry.npmjs.org
   CARGO_REGISTRY: crates.io
 jobs:
+  is_pr:
+    name: Pull Request
+    runs-on: ${{ fromJSON(inputs.runs_on) }}
+    timeout-minutes: 5
+    if: |
+      (
+        github.event.pull_request.head.repo.full_name == github.repository &&
+        github.event_name == 'pull_request'
+      ) || (
+        github.event.pull_request.head.repo.full_name != github.repository &&
+        github.event_name == 'pull_request_target'
+      )
+    steps:
+      - name: Log context
+        env:
+          GITHUB_CONTEXT: ${{ toJSON(github) }}
+        run: echo "${GITHUB_CONTEXT}" || true
+  is_pr_open:
+    name: Pull Request Open
+    runs-on: ${{ fromJSON(inputs.runs_on) }}
+    timeout-minutes: 5
+    needs: is_pr
+    if: github.event.action == 'opened' || github.event.action == 'synchronize'
+    steps:
+      - name: Log context
+        env:
+          GITHUB_CONTEXT: ${{ toJSON(github) }}
+        run: echo "${GITHUB_CONTEXT}" || true
+  is_pr_closed:
+    name: Pull Request Closed
+    runs-on: ${{ fromJSON(inputs.runs_on) }}
+    timeout-minutes: 5
+    needs: is_pr
+    if: github.event.action == 'closed'
+    steps:
+      - name: Log context
+        env:
+          GITHUB_CONTEXT: ${{ toJSON(github) }}
+        run: echo "${GITHUB_CONTEXT}" || true
+  is_pr_merged:
+    name: Pull Request Merged
+    runs-on: ${{ fromJSON(inputs.runs_on) }}
+    timeout-minutes: 5
+    needs: is_pr
+    if: github.event.pull_request.merged == true
+    steps:
+      - name: Log context
+        env:
+          GITHUB_CONTEXT: ${{ toJSON(github) }}
+        run: echo "${GITHUB_CONTEXT}" || true
+  is_push:
+    name: Push
+    runs-on: ${{ fromJSON(inputs.runs_on) }}
+    timeout-minutes: 5
+    if: github.event_name == 'push'
+    steps:
+      - name: Log context
+        env:
+          GITHUB_CONTEXT: ${{ toJSON(github) }}
+        run: echo "${GITHUB_CONTEXT}" || true
+  is_tag_push:
+    name: Push Tag
+    runs-on: ${{ fromJSON(inputs.runs_on) }}
+    timeout-minutes: 5
+    needs: is_push
+    if: |
+      startsWith(github.ref, 'refs/tags/')
+    steps:
+      - name: Log context
+        env:
+          GITHUB_CONTEXT: ${{ toJSON(github) }}
+        run: echo "${GITHUB_CONTEXT}" || true
+  is_tested:
+    name: Do Publish
+    runs-on: ${{ fromJSON(inputs.runs_on) }}
+    timeout-minutes: 5
+    needs:
+      - is_pr_open
+      - npm_test
+      - docker_test
+      - python_test
+      - cargo_test
+      - custom_test
+    if: |
+      !failure() && !cancelled() &&
+      needs.is_pr_open.result == 'success'
+    steps:
+      - name: Log context
+        env:
+          GITHUB_CONTEXT: ${{ toJSON(github) }}
+        run: echo "${GITHUB_CONTEXT}" || true
   context_check:
     name: Check context
     runs-on: ${{ fromJSON(inputs.runs_on) }}
     timeout-minutes: ${{ fromJSON(inputs.jobs_timeout_minutes) }}
+    needs:
+      - is_pr_open
+      - is_tag_push
+      - is_pr_merged
+      - is_pr_closed
     if: |
-      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && inputs.disable_versioning == true) ||
-      (github.event.pull_request.head.repo.full_name == github.repository && github.event_name == 'pull_request') ||
-      (github.event.pull_request.head.repo.full_name != github.repository && github.event_name == 'pull_request_target')
+      !failure() && !cancelled() && (
+        needs.is_pr_open.result == 'success' ||
+        needs.is_tag_push.result == 'success' ||
+        needs.is_pr_merged.result == 'success' ||
+        needs.is_pr_closed.result == 'success'
+      )
     outputs:
       pr: ${{ steps.pr.outcome == 'success' }}
       pr_opened: ${{ steps.pr_opened.outcome == 'success' }}
-      pr_synchronize: ${{ steps.pr_synchronize.outcome == 'success' }}
       pr_merged: ${{ steps.pr_merged.outcome == 'success' }}
       pr_closed: ${{ steps.pr_closed.outcome == 'success' }}
       tagged: ${{ steps.tagged.outcome == 'success' }}
@@ -321,7 +419,17 @@ jobs:
     runs-on: ${{ fromJSON(inputs.runs_on) }}
     timeout-minutes: ${{ fromJSON(inputs.jobs_timeout_minutes) }}
     needs:
-      - context_check
+      - is_pr_open
+      - is_tag_push
+      - is_pr_merged
+      - is_pr_closed
+    if: |
+      !failure() && !cancelled() && (
+        needs.is_pr_open.result == 'success' ||
+        needs.is_tag_push.result == 'success' ||
+        needs.is_pr_merged.result == 'success' ||
+        needs.is_pr_closed.result == 'success'
+      )
     defaults:
       run:
         working-directory: .
@@ -399,6 +507,168 @@ jobs:
         with:
           cmd: bash -c "echo $INPUT | tr -d '[:space:]'"
           separator: ","
+  versioned_source:
+    name: Versioned source
+    runs-on: ${{ fromJSON(inputs.runs_on) }}
+    timeout-minutes: ${{ fromJSON(inputs.jobs_timeout_minutes) }}
+    needs:
+      - is_pr_open
+      - is_tag_push
+      - is_pr_merged
+      - is_pr_closed
+    if: |
+      !failure() && !cancelled() && (
+        needs.is_pr_open.result == 'success' ||
+        needs.is_tag_push.result == 'success' ||
+        needs.is_pr_merged.result == 'success' ||
+        needs.is_pr_closed.result == 'success'
+      )
+    defaults:
+      run:
+        working-directory: .
+        shell: bash --noprofile --norc -eo pipefail -x {0}
+    outputs:
+      new_tag: ${{ steps.new_version.outputs.tag || steps.git_describe.outputs.tag }}
+      version: ${{ steps.new_version.outputs.semver }}
+    steps:
+      - name: Checkout merge branch
+        if: github.event_name == 'pull_request_target' && needs.context_check.outputs.pr_closed != true
+        id: checkout_merge
+        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
+        with:
+          fetch-depth: 0
+          submodules: recursive
+          token: ${{ secrets.FLOWZONE_TOKEN }}
+          ref: refs/pull/${{ github.event.number }}/merge
+      - name: Checkout sha
+        if: steps.checkout_merge.outcome == 'skipped'
+        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
+        with:
+          fetch-depth: 0
+          submodules: recursive
+          token: ${{ secrets.FLOWZONE_TOKEN }}
+      - name: Check external contributor limitations
+        if: github.event.pull_request.head.repo.full_name != github.repository
+        env:
+          GH_TOKEN: ${{ secrets.FLOWZONE_TOKEN }}
+        run: |
+          if [ -n "${{ secrets.COMPOSE_VARS }}" ]
+          then
+            echo "::notice::COMPOSE_VARS secrets are not currently supported for external contributions. \
+              Please contact a member of the organization for assistance."
+            exit 1
+          fi
+
+          if [[ $(gh pr diff ${{ github.event.pull_request.number }} --name-only) =~ ^\.github\/ ]]
+          then
+            echo "::notice::Modifications to workflow files are not supported for external contributions. \
+              Please contact a member of the organization for assistance."
+            exit 1
+          fi
+
+          if [ "${{ inputs.restrict_custom_actions }}" == "true" ]
+          then
+            echo "::notice::Custom actions are disabled for external contributors and will be skipped. \
+              Please contact a member of the organization for assistance."
+            exit 0
+          fi
+      - name: Reject merge commits
+        run: |
+          if [ "$(git cat-file -p ${{ github.event.pull_request.head.sha || github.event.head_commit.id }} | grep '^parent ' | wc -l)" -gt 1 ]
+          then
+            echo "::error::Latest commit appears to be a merge, which is currently unsupported. Try a rebase instead."
+            exit 1
+          fi
+      - name: Import GPG key for signing commits
+        if: inputs.disable_versioning != true && needs.context_check.outputs.pr == 'true'
+        id: import-gpg
+        uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549
+        with:
+          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
+          passphrase: ${{ secrets.GPG_PASSPHRASE }}
+          git_config_global: true
+          git_user_signingkey: true
+          git_commit_gpgsign: true
+      - name: Install versionist
+        if: inputs.disable_versioning != true && needs.context_check.outputs.pr == 'true'
+        run: |
+          npm install -g balena-versionist@0.14.12 versionist@6.9.2
+      - name: Generate changelog
+        if: inputs.disable_versioning != true && needs.context_check.outputs.pr == 'true'
+        run: |
+          if [ ! -f .versionbot/CHANGELOG.yml ]
+          then
+            (cd ${{ runner.temp }}
+
+            wget https://github.com/mikefarah/yq/releases/download/3.0.1/yq_linux_amd64 -O yq
+            echo "a1097c74b81a2ef255583d9718bf4be6  yq" | md5sum -c -
+            chmod +x yq
+
+            PATH="${PWD}:${PATH}" GH_TOKEN=${{ secrets.FLOWZONE_TOKEN }} $(npm root -g)/versionist/scripts/generate-changelog.sh "${GITHUB_WORKSPACE}"
+            )
+          fi
+      - name: Get latest tag for current branch
+        continue-on-error: true
+        id: old_version
+        if: inputs.disable_versioning != true && needs.context_check.outputs.pr == 'true'
+        run: |
+          tag="$(git --no-pager tag --list --sort=-version:refname "v*.*.*" --merged | head -n1)"
+          echo "semver=${tag/v/}" >> $GITHUB_OUTPUT
+          echo "tag=${tag}" >> $GITHUB_OUTPUT
+      - name: Run versionist
+        if: inputs.disable_versioning != true && needs.context_check.outputs.pr == 'true'
+        run: |
+          balena-versionist
+      - name: Git describe
+        id: git_describe
+        run: echo "tag=$(git describe --tags --always --dirty)" >> $GITHUB_OUTPUT
+      - name: Inspect versioned files
+        id: new_version
+        if: inputs.disable_versioning != true && needs.context_check.outputs.pr == 'true'
+        run: |
+          git status --porcelain
+          versions=()
+          [ -f .versionbot/CHANGELOG.yml ] && versions+=($(yq e '.[0].version' .versionbot/CHANGELOG.yml))
+          semver="${versions[0]}"
+          if [ -z "${semver}" ] || [ "${semver}" = "${{ steps.old_version.outputs.semver }}" ]
+          then
+            echo "::error::Failed to detect any versioned files! Did you include a Change-type?"
+            exit 1
+          fi
+
+          echo "semver=${semver}" >> $GITHUB_OUTPUT
+          echo "tag=v${semver}" >> $GITHUB_OUTPUT
+      - name: Create versioned commit
+        if: inputs.disable_versioning != true
+        env:
+          GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
+          GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
+          GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
+          GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}
+          TAG: ${{ steps.new_version.outputs.tag }}
+        run: |
+          git add --all
+          git commit -m "${TAG}"
+          git tag -a "${TAG}" -m "${TAG}" -f
+          git show -1
+          git log -n 2
+      - name: Push versioned commit
+        if: inputs.disable_versioning != true && needs.context_check.outputs.pr_merged == 'true'
+        continue-on-error: true
+        run: |
+          git push origin HEAD:refs/heads/${{ github.base_ref }}
+          # We push the tag separately so that it is only pushed if the commit push succeed, this avoids
+          # issues if something else updates the main branch whilst we're running and causes us to push
+          # the tag successfully but not the main branch and breaks future versioning attempts
+          git push origin "refs/tags/${{ steps.new_version.outputs.tag }}"
+      - name: Compress source
+        run: tar -acvf ${{ runner.temp }}/source.tgz .
+      - name: Upload artifact
+        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
+        with:
+          name: source-${{ github.event.pull_request.head.sha || github.event.head_commit.id }}
+          path: ${{ runner.temp }}/source.tgz
+          retention-days: 1
   npm_check:
     name: Check npm
     runs-on: ${{ fromJSON(inputs.runs_on) }}
@@ -847,158 +1117,6 @@ jobs:
           else
             echo "enabled=false" >> $GITHUB_OUTPUT
           fi
-  versioned_source:
-    name: Versioned source
-    runs-on: ${{ fromJSON(inputs.runs_on) }}
-    timeout-minutes: ${{ fromJSON(inputs.jobs_timeout_minutes) }}
-    needs:
-      - context_check
-    defaults:
-      run:
-        working-directory: .
-        shell: bash --noprofile --norc -eo pipefail -x {0}
-    outputs:
-      new_tag: ${{ steps.new_version.outputs.tag || steps.git_describe.outputs.tag }}
-      version: ${{ steps.new_version.outputs.semver }}
-    steps:
-      - name: Checkout merge branch
-        if: github.event_name == 'pull_request_target' && needs.context_check.outputs.pr_closed != true
-        id: checkout_merge
-        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
-        with:
-          fetch-depth: 0
-          submodules: recursive
-          token: ${{ secrets.FLOWZONE_TOKEN }}
-          ref: refs/pull/${{ github.event.number }}/merge
-      - name: Checkout sha
-        if: steps.checkout_merge.outcome == 'skipped'
-        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
-        with:
-          fetch-depth: 0
-          submodules: recursive
-          token: ${{ secrets.FLOWZONE_TOKEN }}
-      - name: Check external contributor limitations
-        if: github.event.pull_request.head.repo.full_name != github.repository
-        env:
-          GH_TOKEN: ${{ secrets.FLOWZONE_TOKEN }}
-        run: |
-          if [ -n "${{ secrets.COMPOSE_VARS }}" ]
-          then
-            echo "::notice::COMPOSE_VARS secrets are not currently supported for external contributions. \
-              Please contact a member of the organization for assistance."
-            exit 1
-          fi
-
-          if [[ $(gh pr diff ${{ github.event.pull_request.number }} --name-only) =~ ^\.github\/ ]]
-          then
-            echo "::notice::Modifications to workflow files are not supported for external contributions. \
-              Please contact a member of the organization for assistance."
-            exit 1
-          fi
-
-          if [ "${{ inputs.restrict_custom_actions }}" == "true" ]
-          then
-            echo "::notice::Custom actions are disabled for external contributors and will be skipped. \
-              Please contact a member of the organization for assistance."
-            exit 0
-          fi
-      - name: Reject merge commits
-        run: |
-          if [ "$(git cat-file -p ${{ github.event.pull_request.head.sha || github.event.head_commit.id }} | grep '^parent ' | wc -l)" -gt 1 ]
-          then
-            echo "::error::Latest commit appears to be a merge, which is currently unsupported. Try a rebase instead."
-            exit 1
-          fi
-      - name: Import GPG key for signing commits
-        if: inputs.disable_versioning != true && needs.context_check.outputs.pr == 'true'
-        id: import-gpg
-        uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549
-        with:
-          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
-          passphrase: ${{ secrets.GPG_PASSPHRASE }}
-          git_config_global: true
-          git_user_signingkey: true
-          git_commit_gpgsign: true
-      - name: Install versionist
-        if: inputs.disable_versioning != true && needs.context_check.outputs.pr == 'true'
-        run: |
-          npm install -g balena-versionist@0.14.12 versionist@6.9.2
-      - name: Generate changelog
-        if: inputs.disable_versioning != true && needs.context_check.outputs.pr == 'true'
-        run: |
-          if [ ! -f .versionbot/CHANGELOG.yml ]
-          then
-            (cd ${{ runner.temp }}
-
-            wget https://github.com/mikefarah/yq/releases/download/3.0.1/yq_linux_amd64 -O yq
-            echo "a1097c74b81a2ef255583d9718bf4be6  yq" | md5sum -c -
-            chmod +x yq
-
-            PATH="${PWD}:${PATH}" GH_TOKEN=${{ secrets.FLOWZONE_TOKEN }} $(npm root -g)/versionist/scripts/generate-changelog.sh "${GITHUB_WORKSPACE}"
-            )
-          fi
-      - name: Get latest tag for current branch
-        continue-on-error: true
-        id: old_version
-        if: inputs.disable_versioning != true && needs.context_check.outputs.pr == 'true'
-        run: |
-          tag="$(git --no-pager tag --list --sort=-version:refname "v*.*.*" --merged | head -n1)"
-          echo "semver=${tag/v/}" >> $GITHUB_OUTPUT
-          echo "tag=${tag}" >> $GITHUB_OUTPUT
-      - name: Run versionist
-        if: inputs.disable_versioning != true && needs.context_check.outputs.pr == 'true'
-        run: |
-          balena-versionist
-      - name: Git describe
-        id: git_describe
-        run: echo "tag=$(git describe --tags --always --dirty)" >> $GITHUB_OUTPUT
-      - name: Inspect versioned files
-        id: new_version
-        if: inputs.disable_versioning != true && needs.context_check.outputs.pr == 'true'
-        run: |
-          git status --porcelain
-          versions=()
-          [ -f .versionbot/CHANGELOG.yml ] && versions+=($(yq e '.[0].version' .versionbot/CHANGELOG.yml))
-          semver="${versions[0]}"
-          if [ -z "${semver}" ] || [ "${semver}" = "${{ steps.old_version.outputs.semver }}" ]
-          then
-            echo "::error::Failed to detect any versioned files! Did you include a Change-type?"
-            exit 1
-          fi
-
-          echo "semver=${semver}" >> $GITHUB_OUTPUT
-          echo "tag=v${semver}" >> $GITHUB_OUTPUT
-      - name: Create versioned commit
-        if: inputs.disable_versioning != true
-        env:
-          GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
-          GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
-          GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
-          GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}
-          TAG: ${{ steps.new_version.outputs.tag }}
-        run: |
-          git add --all
-          git commit -m "${TAG}"
-          git tag -a "${TAG}" -m "${TAG}" -f
-          git show -1
-          git log -n 2
-      - name: Push versioned commit
-        if: inputs.disable_versioning != true && needs.context_check.outputs.pr_merged == 'true'
-        continue-on-error: true
-        run: |
-          git push origin HEAD:refs/heads/${{ github.base_ref }}
-          # We push the tag separately so that it is only pushed if the commit push succeed, this avoids
-          # issues if something else updates the main branch whilst we're running and causes us to push
-          # the tag successfully but not the main branch and breaks future versioning attempts
-          git push origin "refs/tags/${{ steps.new_version.outputs.tag }}"
-      - name: Compress source
-        run: tar -acvf ${{ runner.temp }}/source.tgz .
-      - name: Upload artifact
-        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
-        with:
-          name: source-${{ github.event.pull_request.head.sha || github.event.head_commit.id }}
-          path: ${{ runner.temp }}/source.tgz
-          retention-days: 1
   npm_test:
     name: Test npm
     runs-on: ${{ fromJSON(inputs.runs_on) }}
@@ -2233,6 +2351,8 @@ jobs:
             echo "Needed job returned result: ${result}"
             exit 1
           done
+
+          exit 1
       - name: Get protection rules
         id: get_protection_rules
         run: |
diff --git a/flowzone.yml b/flowzone.yml
--- a/flowzone.yml
+++ b/flowzone.yml
@@ -44,6 +44,12 @@
       submodules: "recursive"
       token: ${{ secrets.FLOWZONE_TOKEN }}
 
+  - &logContext
+    name: Log context
+    env:
+      GITHUB_CONTEXT: ${{ toJSON(github) }}
+    run: echo "${GITHUB_CONTEXT}" || true
+
 name: Flowzone
 
 on:
@@ -311,20 +317,104 @@ env:
   CARGO_REGISTRY: crates.io
 
 jobs:
+
+  is_pr:
+    name: Pull Request
+    runs-on: ${{ fromJSON(inputs.runs_on) }}
+    timeout-minutes: 5
+    if: |
+      (
+        github.event.pull_request.head.repo.full_name == github.repository &&
+        github.event_name == 'pull_request'
+      ) || (
+        github.event.pull_request.head.repo.full_name != github.repository &&
+        github.event_name == 'pull_request_target'
+      )
+    steps:
+      - *logContext
+
+  is_pr_open:
+    name: Pull Request Open
+    runs-on: ${{ fromJSON(inputs.runs_on) }}
+    timeout-minutes: 5
+    needs: is_pr
+    if: github.event.action == 'opened' || github.event.action == 'synchronize'
+    steps:
+      - *logContext
+
+  is_pr_closed:
+    name: Pull Request Closed
+    runs-on: ${{ fromJSON(inputs.runs_on) }}
+    timeout-minutes: 5
+    needs: is_pr
+    if: github.event.action == 'closed'
+    steps:
+      - *logContext
+
+  is_pr_merged:
+    name: Pull Request Merged
+    runs-on: ${{ fromJSON(inputs.runs_on) }}
+    timeout-minutes: 5
+    needs: is_pr
+    if: github.event.pull_request.merged == true
+    steps:
+      - *logContext
+
+  is_push:
+    name: Push
+    runs-on: ${{ fromJSON(inputs.runs_on) }}
+    timeout-minutes: 5
+    if: github.event_name == 'push'
+    steps:
+      - *logContext
+
+  is_tag_push:
+    name: Push Tag
+    runs-on: ${{ fromJSON(inputs.runs_on) }}
+    timeout-minutes: 5
+    needs: is_push
+    if: |
+      startsWith(github.ref, 'refs/tags/')
+    steps:
+      - *logContext
+
+  is_tested:
+    name: Do Publish
+    runs-on: ${{ fromJSON(inputs.runs_on) }}
+    timeout-minutes: 5
+    needs:
+      - is_pr_open
+      - npm_test
+      - docker_test
+      - python_test
+      - cargo_test
+      - custom_test
+    if: |
+      !failure() && !cancelled() &&
+      needs.is_pr_open.result == 'success'
+    steps:
+      - *logContext
+
   context_check:
     name: Check context
     runs-on: ${{ fromJSON(inputs.runs_on) }}
     timeout-minutes: ${{ fromJSON(inputs.jobs_timeout_minutes) }}
-    # all jobs depend on this one in some way so add global trigger rules here
+    needs:
+      - is_pr_open
+      - is_tag_push
+      - is_pr_merged
+      - is_pr_closed
     if: |
-      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && inputs.disable_versioning == true) ||
-      (github.event.pull_request.head.repo.full_name == github.repository && github.event_name == 'pull_request') ||
-      (github.event.pull_request.head.repo.full_name != github.repository && github.event_name == 'pull_request_target')
+      !failure() && !cancelled() && (
+        needs.is_pr_open.result == 'success' ||
+        needs.is_tag_push.result == 'success' ||
+        needs.is_pr_merged.result == 'success' ||
+        needs.is_pr_closed.result == 'success'
+      )
 
     outputs:
       pr: ${{ steps.pr.outcome == 'success' }}
       pr_opened: ${{ steps.pr_opened.outcome == 'success' }}
-      pr_synchronize: ${{ steps.pr_synchronize.outcome == 'success' }}
       pr_merged: ${{ steps.pr_merged.outcome == 'success' }}
       pr_closed: ${{ steps.pr_closed.outcome == 'success' }}
       tagged: ${{ steps.tagged.outcome == 'success' }}
@@ -341,6 +431,7 @@ jobs:
       JSON: ${{ toJSON(github) }}
 
     steps:
+
       - name: Pull Request
         if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
         id: pr
@@ -381,7 +472,18 @@ jobs:
     name: Sanitize inputs
     runs-on: ${{ fromJSON(inputs.runs_on) }}
     timeout-minutes: ${{ fromJSON(inputs.jobs_timeout_minutes) }}
-    needs: [context_check]
+    needs:
+      - is_pr_open
+      - is_tag_push
+      - is_pr_merged
+      - is_pr_closed
+    if: |
+      !failure() && !cancelled() && (
+        needs.is_pr_open.result == 'success' ||
+        needs.is_tag_push.result == 'success' ||
+        needs.is_pr_merged.result == 'success' ||
+        needs.is_pr_closed.result == 'success'
+      )
 
     defaults:
       run:
@@ -470,6 +572,182 @@ jobs:
         with:
           cmd: bash -c "echo $INPUT | tr -d '[:space:]'"
           separator: ","
+
+  versioned_source:
+    name: Versioned source
+    runs-on: ${{ fromJSON(inputs.runs_on) }}
+    timeout-minutes: ${{ fromJSON(inputs.jobs_timeout_minutes) }}
+    needs:
+      - is_pr_open
+      - is_tag_push
+      - is_pr_merged
+      - is_pr_closed
+    if: |
+      !failure() && !cancelled() && (
+        needs.is_pr_open.result == 'success' ||
+        needs.is_tag_push.result == 'success' ||
+        needs.is_pr_merged.result == 'success' ||
+        needs.is_pr_closed.result == 'success'
+      )
+
+    defaults:
+      run:
+        working-directory: .
+        shell: bash --noprofile --norc -eo pipefail -x {0}
+
+    outputs:
+      new_tag: ${{ steps.new_version.outputs.tag || steps.git_describe.outputs.tag }}
+      version: ${{ steps.new_version.outputs.semver }}
+
+    steps:
+      - *checkoutMergeBranch
+      - *checkoutSha
+
+      # reject external contribution workflow in certain conditions to prevent leaking secrets
+      - name: Check external contributor limitations
+        if: github.event.pull_request.head.repo.full_name != github.repository
+        env:
+          GH_TOKEN: ${{ secrets.FLOWZONE_TOKEN }}
+        run: |
+          if [ -n "${{ secrets.COMPOSE_VARS }}" ]
+          then
+            echo "::notice::COMPOSE_VARS secrets are not currently supported for external contributions. \
+              Please contact a member of the organization for assistance."
+            exit 1
+          fi
+
+          if [[ $(gh pr diff ${{ github.event.pull_request.number }} --name-only) =~ ^\.github\/ ]]
+          then
+            echo "::notice::Modifications to workflow files are not supported for external contributions. \
+              Please contact a member of the organization for assistance."
+            exit 1
+          fi
+
+          if [ "${{ inputs.restrict_custom_actions }}" == "true" ]
+          then
+            echo "::notice::Custom actions are disabled for external contributors and will be skipped. \
+              Please contact a member of the organization for assistance."
+            exit 0
+          fi
+
+      # fail on merge commits (ones with more than one parent)
+      - name: Reject merge commits
+        run: |
+          if [ "$(git cat-file -p ${{ github.event.pull_request.head.sha || github.event.head_commit.id }} | grep '^parent ' | wc -l)" -gt 1 ]
+          then
+            echo "::error::Latest commit appears to be a merge, which is currently unsupported. Try a rebase instead."
+            exit 1
+          fi
+
+      - name: Import GPG key for signing commits
+        if: inputs.disable_versioning != true && needs.context_check.outputs.pr == 'true'
+        id: import-gpg
+        uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549 # v5.2.0
+        with:
+          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
+          passphrase: ${{ secrets.GPG_PASSPHRASE }}
+          git_config_global: true
+          git_user_signingkey: true
+          git_commit_gpgsign: true
+
+      - name: Install versionist
+        if: inputs.disable_versioning != true && needs.context_check.outputs.pr == 'true'
+        run: |
+          npm install -g balena-versionist@0.14.12 versionist@6.9.2
+
+      - name: Generate changelog
+        if: inputs.disable_versioning != true && needs.context_check.outputs.pr == 'true'
+        run: |
+          if [ ! -f .versionbot/CHANGELOG.yml ]
+          then
+            (cd ${{ runner.temp }}
+
+            wget https://github.com/mikefarah/yq/releases/download/3.0.1/yq_linux_amd64 -O yq
+            echo "a1097c74b81a2ef255583d9718bf4be6  yq" | md5sum -c -
+            chmod +x yq
+
+            PATH="${PWD}:${PATH}" GH_TOKEN=${{ secrets.FLOWZONE_TOKEN }} $(npm root -g)/versionist/scripts/generate-changelog.sh "${GITHUB_WORKSPACE}"
+            )
+          fi
+
+      # parse last versioned commit from tags so we can check for changes
+      # this step can fail if there has never been a versioned PR merged
+      - name: Get latest tag for current branch
+        continue-on-error: true
+        id: old_version
+        if: inputs.disable_versioning != true && needs.context_check.outputs.pr == 'true'
+        run: |
+          tag="$(git --no-pager tag --list --sort=-version:refname "v*.*.*" --merged | head -n1)"
+          echo "semver=${tag/v/}" >> $GITHUB_OUTPUT
+          echo "tag=${tag}" >> $GITHUB_OUTPUT
+
+      # install and run versionist via balena-versionist
+      - name: Run versionist
+        if: inputs.disable_versioning != true && needs.context_check.outputs.pr == 'true'
+        run: |
+          balena-versionist
+
+      # set a tag to be used as a fallback if versioning is disabled
+      - name: Git describe
+        id: git_describe
+        run: echo "tag=$(git describe --tags --always --dirty)" >> $GITHUB_OUTPUT
+
+      # inspect all known versioned files to extract the new version
+      # TODO: versionist should provide the new version via stdout!
+      - name: Inspect versioned files
+        id: new_version
+        if: inputs.disable_versioning != true && needs.context_check.outputs.pr == 'true'
+        run: |
+          git status --porcelain
+          versions=()
+          [ -f .versionbot/CHANGELOG.yml ] && versions+=($(yq e '.[0].version' .versionbot/CHANGELOG.yml))
+          semver="${versions[0]}"
+          if [ -z "${semver}" ] || [ "${semver}" = "${{ steps.old_version.outputs.semver }}" ]
+          then
+            echo "::error::Failed to detect any versioned files! Did you include a Change-type?"
+            exit 1
+          fi
+
+          echo "semver=${semver}" >> $GITHUB_OUTPUT
+          echo "tag=v${semver}" >> $GITHUB_OUTPUT
+
+      # create a versioned commit
+      - name: Create versioned commit
+        if: inputs.disable_versioning != true
+        env:
+          GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
+          GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
+          GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
+          GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}
+          TAG: ${{ steps.new_version.outputs.tag }}
+        run: |
+          git add --all
+          git commit -m "${TAG}"
+          git tag -a "${TAG}" -m "${TAG}" -f
+          git show -1
+          git log -n 2
+
+      # push the versioned commit only if the PR is merged
+      - name: Push versioned commit
+        if: inputs.disable_versioning != true && needs.context_check.outputs.pr_merged == 'true'
+        continue-on-error: true
+        run: |
+          git push origin HEAD:refs/heads/${{ github.base_ref }}
+          # We push the tag separately so that it is only pushed if the commit push succeed, this avoids
+          # issues if something else updates the main branch whilst we're running and causes us to push
+          # the tag successfully but not the main branch and breaks future versioning attempts
+          git push origin "refs/tags/${{ steps.new_version.outputs.tag }}"
+
+      # https://github.com/actions/upload-artifact#maintaining-file-permissions-and-case-sensitive-files
+      - name: Compress source
+        run: tar -acvf ${{ runner.temp }}/source.tgz .
+
+      - name: Upload artifact
+        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
+        with:
+          name: source-${{ github.event.pull_request.head.sha || github.event.head_commit.id }}
+          path: ${{ runner.temp }}/source.tgz
+          retention-days: 1
 
   # check if the repository has a package.json file and which engine versions are supported
   npm_check:
@@ -922,171 +1200,6 @@ jobs:
           else
             echo "enabled=false" >> $GITHUB_OUTPUT
           fi
-
-  versioned_source:
-    name: Versioned source
-    runs-on: ${{ fromJSON(inputs.runs_on) }}
-    timeout-minutes: ${{ fromJSON(inputs.jobs_timeout_minutes) }}
-    needs: [context_check]
-
-    defaults:
-      run:
-        working-directory: .
-        shell: bash --noprofile --norc -eo pipefail -x {0}
-
-    outputs:
-      new_tag: ${{ steps.new_version.outputs.tag || steps.git_describe.outputs.tag }}
-      version: ${{ steps.new_version.outputs.semver }}
-
-    steps:
-      - *checkoutMergeBranch
-      - *checkoutSha
-
-      # reject external contribution workflow in certain conditions to prevent leaking secrets
-      - name: Check external contributor limitations
-        if: github.event.pull_request.head.repo.full_name != github.repository
-        env:
-          GH_TOKEN: ${{ secrets.FLOWZONE_TOKEN }}
-        run: |
-          if [ -n "${{ secrets.COMPOSE_VARS }}" ]
-          then
-            echo "::notice::COMPOSE_VARS secrets are not currently supported for external contributions. \
-              Please contact a member of the organization for assistance."
-            exit 1
-          fi
-
-          if [[ $(gh pr diff ${{ github.event.pull_request.number }} --name-only) =~ ^\.github\/ ]]
-          then
-            echo "::notice::Modifications to workflow files are not supported for external contributions. \
-              Please contact a member of the organization for assistance."
-            exit 1
-          fi
-
-          if [ "${{ inputs.restrict_custom_actions }}" == "true" ]
-          then
-            echo "::notice::Custom actions are disabled for external contributors and will be skipped. \
-              Please contact a member of the organization for assistance."
-            exit 0
-          fi
-
-      # fail on merge commits (ones with more than one parent)
-      - name: Reject merge commits
-        run: |
-          if [ "$(git cat-file -p ${{ github.event.pull_request.head.sha || github.event.head_commit.id }} | grep '^parent ' | wc -l)" -gt 1 ]
-          then
-            echo "::error::Latest commit appears to be a merge, which is currently unsupported. Try a rebase instead."
-            exit 1
-          fi
-
-      - name: Import GPG key for signing commits
-        if: inputs.disable_versioning != true && needs.context_check.outputs.pr == 'true'
-        id: import-gpg
-        uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549 # v5.2.0
-        with:
-          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
-          passphrase: ${{ secrets.GPG_PASSPHRASE }}
-          git_config_global: true
-          git_user_signingkey: true
-          git_commit_gpgsign: true
-
-      - name: Install versionist
-        if: inputs.disable_versioning != true && needs.context_check.outputs.pr == 'true'
-        run: |
-          npm install -g balena-versionist@0.14.12 versionist@6.9.2
-
-      - name: Generate changelog
-        if: inputs.disable_versioning != true && needs.context_check.outputs.pr == 'true'
-        run: |
-          if [ ! -f .versionbot/CHANGELOG.yml ]
-          then
-            (cd ${{ runner.temp }}
-
-            wget https://github.com/mikefarah/yq/releases/download/3.0.1/yq_linux_amd64 -O yq
-            echo "a1097c74b81a2ef255583d9718bf4be6  yq" | md5sum -c -
-            chmod +x yq
-
-            PATH="${PWD}:${PATH}" GH_TOKEN=${{ secrets.FLOWZONE_TOKEN }} $(npm root -g)/versionist/scripts/generate-changelog.sh "${GITHUB_WORKSPACE}"
-            )
-          fi
-
-      # parse last versioned commit from tags so we can check for changes
-      # this step can fail if there has never been a versioned PR merged
-      - name: Get latest tag for current branch
-        continue-on-error: true
-        id: old_version
-        if: inputs.disable_versioning != true && needs.context_check.outputs.pr == 'true'
-        run: |
-          tag="$(git --no-pager tag --list --sort=-version:refname "v*.*.*" --merged | head -n1)"
-          echo "semver=${tag/v/}" >> $GITHUB_OUTPUT
-          echo "tag=${tag}" >> $GITHUB_OUTPUT
-
-      # install and run versionist via balena-versionist
-      - name: Run versionist
-        if: inputs.disable_versioning != true && needs.context_check.outputs.pr == 'true'
-        run: |
-          balena-versionist
-
-      # set a tag to be used as a fallback if versioning is disabled
-      - name: Git describe
-        id: git_describe
-        run: echo "tag=$(git describe --tags --always --dirty)" >> $GITHUB_OUTPUT
-
-      # inspect all known versioned files to extract the new version
-      # TODO: versionist should provide the new version via stdout!
-      - name: Inspect versioned files
-        id: new_version
-        if: inputs.disable_versioning != true && needs.context_check.outputs.pr == 'true'
-        run: |
-          git status --porcelain
-          versions=()
-          [ -f .versionbot/CHANGELOG.yml ] && versions+=($(yq e '.[0].version' .versionbot/CHANGELOG.yml))
-          semver="${versions[0]}"
-          if [ -z "${semver}" ] || [ "${semver}" = "${{ steps.old_version.outputs.semver }}" ]
-          then
-            echo "::error::Failed to detect any versioned files! Did you include a Change-type?"
-            exit 1
-          fi
-
-          echo "semver=${semver}" >> $GITHUB_OUTPUT
-          echo "tag=v${semver}" >> $GITHUB_OUTPUT
-
-      # create a versioned commit
-      - name: Create versioned commit
-        if: inputs.disable_versioning != true
-        env:
-          GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
-          GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
-          GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
-          GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}
-          TAG: ${{ steps.new_version.outputs.tag }}
-        run: |
-          git add --all
-          git commit -m "${TAG}"
-          git tag -a "${TAG}" -m "${TAG}" -f
-          git show -1
-          git log -n 2
-
-      # push the versioned commit only if the PR is merged
-      - name: Push versioned commit
-        if: inputs.disable_versioning != true && needs.context_check.outputs.pr_merged == 'true'
-        continue-on-error: true
-        run: |
-          git push origin HEAD:refs/heads/${{ github.base_ref }}
-          # We push the tag separately so that it is only pushed if the commit push succeed, this avoids
-          # issues if something else updates the main branch whilst we're running and causes us to push
-          # the tag successfully but not the main branch and breaks future versioning attempts
-          git push origin "refs/tags/${{ steps.new_version.outputs.tag }}"
-
-      # https://github.com/actions/upload-artifact#maintaining-file-permissions-and-case-sensitive-files
-      - name: Compress source
-        run: tar -acvf ${{ runner.temp }}/source.tgz .
-
-      - name: Upload artifact
-        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
-        with:
-          name: source-${{ github.event.pull_request.head.sha || github.event.head_commit.id }}
-          path: ${{ runner.temp }}/source.tgz
-          retention-days: 1
 
   ###################################################
   ## npm
@@ -2392,6 +2505,8 @@ jobs:
             echo "Needed job returned result: ${result}"
             exit 1
           done
+
+          exit 1
 
       - name: Get protection rules
         id: get_protection_rules
