Create .versionbot/CHANGELOG.yml if it does not exist
This is the preferred way to parse the latest version, and also
enables embedded changelogs when consumed by another project using
versionist.

Change-type: patch
Signed-off-by: Kyle Harding <kyle@balena.io>

diff --git a/.github/workflows/flowzone.yml b/.github/workflows/flowzone.yml
--- a/.github/workflows/flowzone.yml
+++ b/.github/workflows/flowzone.yml
@@ -402,8 +402,8 @@ jobs:
         shell: ${{ needs.context_check.outputs.shell }}
 
     outputs:
-      new_tag: ${{ steps.version_check.outputs.new_tag }}
-      version: ${{ steps.version_check.outputs.version }}
+      new_tag: ${{ steps.versionist.outputs.new_tag }}
+      version: ${{ steps.versionist.outputs.version }}
 
     steps:
       - name: Checkout source
@@ -423,8 +423,9 @@ jobs:
           git_user_signingkey: true
           git_commit_gpgsign: true
 
-      # install and run versionist and balena-versionist
-      # extract the latest version from the changelog
+      # install and run versionist via balena-versionist
+      # create changelog yaml if it does not exist (TODO: versionist should handle this automatically)
+      # exit if versionist didn't change anything
       - name: Run versionist
         if: needs.project_types.outputs.repo_type != '' && github.event_name == 'pull_request'
         id: versionist
@@ -433,35 +434,45 @@ jobs:
           balena-versionist
           git status --porcelain
 
-      # exit if versionist didn't change anything or the changelog could not be parsed
-      - name: Check versionist results
-        if: needs.project_types.outputs.repo_type != '' && github.event_name == 'pull_request'
-        id: version_check
-        run: |
           test -n "$(git status --porcelain)" || { echo "Failed to version any files, did you include a Change-type?" ; exit 1 ; }
-          version="$(grep -E '^# v[0-9]+\.[0-9]+\.[0-9]+|^## [0-9]+\.[0-9]+\.[0-9]+' CHANGELOG.md | head -n1 | awk '{print $2}' | tr -d 'v')"
-          test -n "${version}" || { echo "Failed to parse version from changelog!" ; exit 1 ; }
+
+          if [ ! -f .versionbot/CHANGELOG.yml ]
+          then
+            wget https://raw.githubusercontent.com/product-os/versionist/master/scripts/generate-changelog.sh
+            echo "c1d25c8d5dc40e08a13c43ac93582661  generate-changelog.sh" | md5sum -c -
+            chmod +x generate-changelog.sh
+
+            wget https://github.com/mikefarah/yq/releases/download/3.0.1/yq_linux_amd64 -O yq
+            echo "a1097c74b81a2ef255583d9718bf4be6  yq" | md5sum -c -
+            chmod +x yq
+
+            PATH="${PWD}:${PATH}" GH_TOKEN=${{ secrets.FLOWZONE_TOKEN }} ./generate-changelog.sh .
+            rm yq generate-changelog.sh
+          fi
+
+          version="$(yq e '.[0].version' -r .versionbot/CHANGELOG.yml)"
+          test -n "${version}" || { echo "Failed to get version from changelog!" ; exit 1 ; }
           echo "::set-output name=version::${version}"
           echo "::set-output name=new_tag::v${version}"
 
-      # create a versioned commit only if the the version has changed
+      # create a versioned commit
       - name: Create versioned commit
-        if: steps.version_check.outputs.new_tag != ''
+        if: steps.versionist.outputs.new_tag != ''
         env:
           GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
           GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
           GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
           GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}
-          TAG: ${{ steps.version_check.outputs.new_tag }}
+          TAG: ${{ steps.versionist.outputs.new_tag }}
         run: |
           git add --all
-          git commit -m "${TAG}" --allow-empty
+          git commit -m "${TAG}"
           git tag -a "${TAG}" -m "${TAG}" -f
           git log -n 2
 
       # push the versioned commit only if the PR is merged
       - name: Push versioned commit
-        if: github.event.pull_request.merged == true && steps.version_check.outputs.new_tag != ''
+        if: github.event.pull_request.merged == true && steps.versionist.outputs.new_tag != ''
         run: |
           git push origin HEAD:${{ github.base_ref }} --follow-tags
 
