adds release notes into PR as a comment
* update production floating tag
* add balena-deploy-request dependency

change-type: patch

diff --git a/.github/workflows/flowzone.yml b/.github/workflows/flowzone.yml
--- a/.github/workflows/flowzone.yml
+++ b/.github/workflows/flowzone.yml
@@ -279,6 +279,11 @@ on:
         type: string
         required: false
         default: ok-to-test
+      release_notes:
+        description: Create git tags and a PR comment with detailed change log.
+        type: boolean
+        required: false
+        default: false
 concurrency:
   group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
   cancel-in-progress: ${{ github.event.action == 'synchronize' }}
@@ -441,12 +446,13 @@ jobs:
         uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
         with:
           node-version: 18.x
-      - name: Install versionist
+      - name: Install versioning tools
         if: inputs.disable_versioning != true
         run: |
-          npm install -g balena-versionist@~0.14.13 versionist@^7.0.3
-          npm ls -g balena-versionist
-          npm ls -g versionist
+          cat <package.json | jq -r '.dependencies | to_entries[] | .key + "@" + .value' \
+            | xargs -L1 npm install -g
+
+          npm ls -g
       - name: Generate changelog
         if: inputs.disable_versioning != true
         env:
@@ -566,31 +572,111 @@ jobs:
           echo "$response" | jq .
           echo "sha=$(echo $response | jq -r .sha)" >> $GITHUB_OUTPUT
           echo "json=$(echo $response | jq -c .)" >> $GITHUB_OUTPUT
-      - name: Update branch reference
+      - name: Update git reference
         if: github.event.pull_request.merged == true && steps.create_commit.outputs.sha != ''
         env:
           GH_TOKEN: ${{ steps.gh_app_token.outputs.token || secrets.FLOWZONE_TOKEN }}
+          REF: /repos/$GH_REPO/git/refs/heads/${{ github.base_ref }}
         run: |
           gh api \
             -X PATCH \
             -H "Accept: application/vnd.github+json" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
-            /repos/$GH_REPO/git/refs/heads/${{ github.base_ref }} \
+            "${REF}" \
             -f sha='${{ steps.create_commit.outputs.sha }}' \
             -F force=true \
             --include
-      - name: Create tag reference
+      - name: Create git reference
         if: github.event.pull_request.merged == true && steps.create_tag.outputs.sha != ''
         env:
           GH_TOKEN: ${{ steps.gh_app_token.outputs.token || secrets.FLOWZONE_TOKEN }}
+          REF: refs/tags/${{ steps.versionist.outputs.tag }}
         run: |
           gh api \
             -X POST \
             -H "Accept: application/vnd.github+json" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             /repos/$GH_REPO/git/refs \
-            -f ref='refs/tags/${{ steps.versionist.outputs.tag }}' \
+            -f ref="${REF}" \
             -f sha='${{ steps.create_tag.outputs.sha }}' \
+            --include
+      - name: Generate GitHub App installation token
+        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a
+        continue-on-error: true
+        id: pull_requests_write_token
+        with:
+          app_id: ${{ inputs.app_id }}
+          installation_retrieval_mode: id
+          installation_retrieval_payload: ${{ inputs.installation_id }}
+          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
+          permissions: |-
+            {
+              "contents": "read",
+              "metadata": "read",
+              "pull_requests": "write"
+            }
+      - name: Draft PR comment
+        if: inputs.disable_versioning != true && inputs.release_notes == true
+        continue-on-error: true
+        env:
+          GH_TOKEN: ${{ steps.pull_requests_write_token.outputs.token }}
+        run: |
+          release_notes="$(mktemp)"
+          npx balena-deploy-request >"${release_notes}"
+
+          if [[ $? -eq 0 ]]; then
+              if ! cat <"${release_notes}" | gh pr comment --edit-last ${{ github.event.pull_request.number }} --body-file -; then
+                  cat <"${release_notes}" | gh pr comment ${{ github.event.pull_request.number }} --body-file -
+                  if [[ $? -gt 0 ]]; then
+                      echo '::warning:: Error drafting release notes PR comment.'
+                  fi
+              fi
+          fi
+      - name: Get and format timestamp
+        id: timestamp
+        env:
+          FORMAT: "%Y-%m-%d-%H%M%S"
+        run: |
+          echo "datetime=$(date +"${FORMAT}")" >> $GITHUB_OUTPUT
+        if: |
+          github.event.pull_request.merged == true
+          && steps.create_commit.outputs.sha != ''
+          && inputs.disable_versioning != true
+          && inputs.release_notes == true
+      - name: Create git reference
+        if: |
+          github.event.pull_request.merged == true
+          && steps.create_commit.outputs.sha != ''
+          && inputs.disable_versioning != true
+          && inputs.release_notes == true
+        env:
+          REF: refs/tags/production-${{ steps.timestamp.outputs.datetime }}
+        run: |
+          gh api \
+            -X POST \
+            -H "Accept: application/vnd.github+json" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            /repos/$GH_REPO/git/refs \
+            -f ref="${REF}" \
+            -f sha='${{ steps.create_tag.outputs.sha }}' \
+            --include
+        continue-on-error: true
+      - name: Update git reference
+        if: |
+          github.event.pull_request.merged == true
+          && steps.create_commit.outputs.sha != ''
+          && inputs.disable_versioning != true
+          && inputs.release_notes == true
+        env:
+          REF: /repos/$GH_REPO/git/refs/tags/production-${{ steps.timestamp.outputs.datetime }}
+        run: |
+          gh api \
+            -X PATCH \
+            -H "Accept: application/vnd.github+json" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            "${REF}" \
+            -f sha='${{ steps.create_commit.outputs.sha }}' \
+            -F force=true \
             --include
   is_npm:
     name: Is npm
@@ -2532,7 +2618,7 @@ jobs:
           submodules: recursive
           ref: ${{ needs.versioned_source.outputs.sha }}
           token: ${{ steps.gh_app_token.outputs.token || secrets.FLOWZONE_TOKEN }}
-      - name: Generate release notes
+      - name: Generate short release note
         id: release_notes
         env:
           look_back: 1
@@ -2614,7 +2700,7 @@ jobs:
           submodules: recursive
           ref: ${{ needs.versioned_source.outputs.sha }}
           token: ${{ steps.gh_app_token.outputs.token || secrets.FLOWZONE_TOKEN }}
-      - name: Generate release notes
+      - name: Generate short release note
         id: release_notes
         env:
           look_back: 2
@@ -3024,7 +3110,7 @@ jobs:
           submodules: recursive
           ref: ${{ needs.versioned_source.outputs.sha }}
           token: ${{ steps.gh_app_token.outputs.token || secrets.FLOWZONE_TOKEN }}
-      - name: Generate release notes
+      - name: Generate short release note
         id: release_notes
         env:
           look_back: 1
@@ -3102,7 +3188,7 @@ jobs:
           submodules: recursive
           ref: ${{ needs.versioned_source.outputs.sha }}
           token: ${{ steps.gh_app_token.outputs.token || secrets.FLOWZONE_TOKEN }}
-      - name: Generate release notes
+      - name: Generate short release note
         id: release_notes
         env:
           look_back: 2
diff --git a/flowzone.yml b/flowzone.yml
--- a/flowzone.yml
+++ b/flowzone.yml
@@ -81,7 +81,7 @@
         }
 
   - &getReleaseNotes
-    name: Generate release notes
+    name: Generate short release note
     id: release_notes
     env:
       look_back: 1
@@ -101,6 +101,48 @@
 
       echo "${release_notes}" > "${release_notes_file}"
       echo "file=${release_notes_file}" >> $GITHUB_OUTPUT
+
+  - &getTimeStamp
+    name: Get and format timestamp
+    id: timestamp
+    env:
+      FORMAT: '%Y-%m-%d-%H%M%S'
+    run: |
+      echo "datetime=$(date +"${FORMAT}")" >> $GITHUB_OUTPUT
+
+  # https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#update-a-reference
+  - &updateGitReference
+    name: Update git reference
+    if: github.event.pull_request.merged == true && steps.create_commit.outputs.sha != ''
+    env:
+      GH_TOKEN: ${{ steps.gh_app_token.outputs.token || secrets.FLOWZONE_TOKEN }}
+      REF: '/repos/$GH_REPO/git/refs/heads/${{ github.base_ref }}'
+    run: |
+      gh api \
+        -X PATCH \
+        -H "Accept: application/vnd.github+json" \
+        -H "X-GitHub-Api-Version: 2022-11-28" \
+        "${REF}" \
+        -f sha='${{ steps.create_commit.outputs.sha }}' \
+        -F force=true \
+        --include
+
+  # https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#create-a-reference
+  - &createGitReference
+    name: Create git reference
+    if: github.event.pull_request.merged == true && steps.create_tag.outputs.sha != ''
+    env:
+      GH_TOKEN: ${{ steps.gh_app_token.outputs.token || secrets.FLOWZONE_TOKEN }}
+      REF: 'refs/tags/${{ steps.versionist.outputs.tag }}'
+    run: |
+      gh api \
+        -X POST \
+        -H "Accept: application/vnd.github+json" \
+        -H "X-GitHub-Api-Version: 2022-11-28" \
+        /repos/$GH_REPO/git/refs \
+        -f ref="${REF}" \
+        -f sha='${{ steps.create_tag.outputs.sha }}' \
+        --include
 
   - &checkoutMergeRef
     # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
@@ -923,6 +965,11 @@ on:
         type: string
         required: false
         default: "ok-to-test"
+      release_notes:
+        description: "Create git tags and a PR comment with detailed change log."
+        type: boolean
+        required: false
+        default: false
 
 # https://docs.github.com/en/actions/using-jobs/using-concurrency
 concurrency:
@@ -1032,12 +1079,13 @@ jobs:
         with:
           node-version: 18.x
 
-      - name: Install versionist
+      - name: Install versioning tools
         if: inputs.disable_versioning != true
         run: |
-          npm install -g balena-versionist@~0.14.13 versionist@^7.0.3
-          npm ls -g balena-versionist
-          npm ls -g versionist
+          cat <package.json | jq -r '.dependencies | to_entries[] | .key + "@" + .value' \
+            | xargs -L1 npm install -g
+
+          npm ls -g
 
       - name: Generate changelog
         if: inputs.disable_versioning != true
@@ -1170,35 +1218,64 @@ jobs:
           echo "sha=$(echo $response | jq -r .sha)" >> $GITHUB_OUTPUT
           echo "json=$(echo $response | jq -c .)" >> $GITHUB_OUTPUT
 
-      # https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#update-a-reference
-      - name: Update branch reference
-        if: github.event.pull_request.merged == true && steps.create_commit.outputs.sha != ''
-        env:
-          GH_TOKEN: ${{ steps.gh_app_token.outputs.token || secrets.FLOWZONE_TOKEN }}
-        run: |
-          gh api \
-            -X PATCH \
-            -H "Accept: application/vnd.github+json" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            /repos/$GH_REPO/git/refs/heads/${{ github.base_ref }} \
-            -f sha='${{ steps.create_commit.outputs.sha }}' \
-            -F force=true \
-            --include
+      - *updateGitReference
+      - *createGitReference
 
-      # https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#create-a-reference
-      - name: Create tag reference
-        if: github.event.pull_request.merged == true && steps.create_tag.outputs.sha != ''
+      - <<: *getGitHubAppToken
+        id: pull_requests_write_token
+        with:
+          <<: *getGitHubAppTokenWith
+          permissions: >-
+            {
+              "contents": "read",
+              "metadata": "read",
+              "pull_requests": "write"
+            }
+
+      - name: Draft PR comment
+        if: inputs.disable_versioning != true && inputs.release_notes == true
+        continue-on-error: true
         env:
-          GH_TOKEN: ${{ steps.gh_app_token.outputs.token || secrets.FLOWZONE_TOKEN }}
+          GH_TOKEN: ${{ steps.pull_requests_write_token.outputs.token }}
         run: |
-          gh api \
-            -X POST \
-            -H "Accept: application/vnd.github+json" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            /repos/$GH_REPO/git/refs \
-            -f ref='refs/tags/${{ steps.versionist.outputs.tag }}' \
-            -f sha='${{ steps.create_tag.outputs.sha }}' \
-            --include
+          release_notes="$(mktemp)"
+          npx balena-deploy-request >"${release_notes}"
+
+          if [[ $? -eq 0 ]]; then
+              if ! cat <"${release_notes}" | gh pr comment --edit-last ${{ github.event.pull_request.number }} --body-file -; then
+                  cat <"${release_notes}" | gh pr comment ${{ github.event.pull_request.number }} --body-file -
+                  if [[ $? -gt 0 ]]; then
+                      echo '::warning:: Error drafting release notes PR comment.'
+                  fi
+              fi
+          fi
+
+      - <<: *getTimeStamp
+        if: |
+          github.event.pull_request.merged == true
+          && steps.create_commit.outputs.sha != ''
+          && inputs.disable_versioning != true
+          && inputs.release_notes == true
+
+      # required by https://github.com/balena-io-modules/balena-deploy-request
+      - <<: *createGitReference
+        if: |
+          github.event.pull_request.merged == true
+          && steps.create_commit.outputs.sha != ''
+          && inputs.disable_versioning != true
+          && inputs.release_notes == true
+        continue-on-error: true
+        env:
+          REF: 'refs/tags/production-${{ steps.timestamp.outputs.datetime }}'
+
+      - <<: *updateGitReference
+        if: |
+          github.event.pull_request.merged == true
+          && steps.create_commit.outputs.sha != ''
+          && inputs.disable_versioning != true
+          && inputs.release_notes == true
+        env:
+          REF: '/repos/$GH_REPO/git/refs/tags/production-${{ steps.timestamp.outputs.datetime }}'
 
   # check if the repository has a package.json file and which engine versions are supported
   is_npm:
@@ -2446,7 +2523,7 @@ jobs:
     steps:
       - *getGitHubAppToken
       - *checkoutVersionedSha
-      - <<: *getReleaseNotes
+      - *getReleaseNotes
       - *createLocalRefs
       - *deployToBalenaAction
 
@@ -2473,6 +2550,7 @@ jobs:
       - <<: *getReleaseNotes
         env:
           look_back: 2
+
       - *deployToBalenaAction
 
   ###################################################
@@ -2733,7 +2811,7 @@ jobs:
 
       - *deleteDraftGitHubRelease
       - *checkoutVersionedSha
-      - <<: *getReleaseNotes
+      - *getReleaseNotes
 
       - name: Download all artifacts
         uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
