Enable shell tracing across all jobs
Change-type: patch
Signed-off-by: Kyle Harding <kyle@balena.io>

diff --git a/.github/workflows/flowzone.yml b/.github/workflows/flowzone.yml
--- a/.github/workflows/flowzone.yml
+++ b/.github/workflows/flowzone.yml
@@ -136,6 +136,7 @@ jobs:
       node_versions: ${{ steps.node_versions.outputs.build }}
       ghcr_repo: ${{ steps.ghcr_repo.outputs.value }}
       dockerhub_repo: ${{ steps.dockerhub_repo.outputs.value }}
+      shell: ${{ steps.shell.outputs.value || 'bash' }}
 
     steps:
       # - name: Dump GitHub context
@@ -175,6 +176,12 @@ jobs:
         run: |
           echo "::set-output name=value::$(echo docker.io/${{ inputs.dockerhub_repo }})"
 
+      - name: Enable shell tracing
+        if: inputs.verbose == true
+        id: shell
+        run: |
+          echo "::set-output name=value::$(echo 'bash --noprofile --norc -eo pipefail -x {0}')"
+
   source_check:
     name: Source check
     runs-on: ubuntu-latest
@@ -183,7 +190,7 @@ jobs:
     defaults:
       run:
         working-directory: ${{ inputs.working_directory }}
-        shell: bash
+        shell: ${{ needs.context_check.outputs.shell }}
 
     outputs:
       npm: ${{ steps.npm.outputs.enabled }}
@@ -240,7 +247,7 @@ jobs:
     defaults:
       run:
         working-directory: .
-        shell: bash
+        shell: ${{ needs.context_check.outputs.shell }}
 
     steps:
       - name: Apply branch protection rules
@@ -301,7 +308,7 @@ jobs:
     defaults:
       run:
         working-directory: .
-        shell: bash
+        shell: ${{ needs.context_check.outputs.shell }}
 
     outputs:
       tag: ${{ steps.versionist.outputs.tag }}
@@ -392,7 +399,7 @@ jobs:
     defaults:
       run:
         working-directory: ${{ inputs.working_directory }}
-        shell: bash
+        shell: ${{ needs.context_check.outputs.shell }}
 
     strategy:
       fail-fast: false
@@ -431,7 +438,7 @@ jobs:
   npm_draft:
     name: npm draft
     runs-on: ubuntu-latest
-    needs: [npm_matrix, versioned_source]
+    needs: [context_check, npm_matrix, versioned_source]
     if: |
       inputs.npm_registry != '' &&
       github.event_name == 'pull_request' &&
@@ -440,7 +447,7 @@ jobs:
     defaults:
       run:
         working-directory: ${{ inputs.working_directory }}
-        shell: bash
+        shell: ${{ needs.context_check.outputs.shell }}
 
     steps:
       - name: Download versioned source
@@ -454,11 +461,6 @@ jobs:
 
       - name: Publish draft tag
         run: |
-          if [[ '${{ inputs.verbose }}' =~ 1|on|On|Yes|yes|true|True ]]; then
-            set -x
-            env
-          fi
-
           echo '//${{ inputs.npm_registry }}/:_authToken=${{ secrets.NPM_TOKEN }}' > ~/.npmrc
 
           npm whoami
@@ -502,7 +504,7 @@ jobs:
     defaults:
       run:
         working-directory: ${{ inputs.working_directory }}
-        shell: bash
+        shell: ${{ needs.context_check.outputs.shell }}
 
     steps:
       - name: Download versioned source
@@ -516,11 +518,6 @@ jobs:
 
       - name: Publish to registry
         run: |
-          if [[ '${{ inputs.verbose }}' =~ 1|on|On|Yes|yes|true|True ]]; then
-            set -x
-            env
-          fi
-
           echo '//${{ inputs.npm_registry }}/:_authToken=${{ secrets.NPM_TOKEN }}' > ~/.npmrc
 
           npm whoami
@@ -551,7 +548,7 @@ jobs:
     defaults:
       run:
         working-directory: ${{ inputs.working_directory }}
-        shell: bash
+        shell: ${{ needs.context_check.outputs.shell }}
 
     env:
       COMPOSE_VARS: ${{ secrets.COMPOSE_VARS }}
@@ -674,7 +671,7 @@ jobs:
     defaults:
       run:
         working-directory: .
-        shell: bash
+        shell: ${{ needs.context_check.outputs.shell }}
 
     steps:
       - name: Login to GitHub Container Registry
@@ -748,7 +745,7 @@ jobs:
     defaults:
       run:
         working-directory: .
-        shell: bash
+        shell: ${{ needs.context_check.outputs.shell }}
 
     steps:
       - name: Login to GitHub Container Registry
@@ -838,7 +835,7 @@ jobs:
     defaults:
       run:
         working-directory: ${{ inputs.working_directory }}
-        shell: bash
+        shell: ${{ needs.context_check.outputs.shell }}
 
     steps:
       - name: Download versioned source
@@ -860,12 +857,12 @@ jobs:
   balena_all:
     name: balena all
     runs-on: ubuntu-latest
-    needs: [balena_matrix]
+    needs: [context_check, balena_matrix]
 
     defaults:
       run:
         working-directory: .
-        shell: bash
+        shell: ${{ needs.context_check.outputs.shell }}
 
     steps:
       # just a catchall to ensure the matrix was successful so we can use this job as
