Mark All jobs as failed on PR closed events
This job is used for branch requirements, and
we don't want it to show as skipped in case the PR
is ever reopened.

See: https://github.com/product-os/flowzone/issues/1143

Change-type: minor
Signed-off-by: Kyle Harding <kyle@balena.io>

diff --git a/.github/workflows/flowzone.yml b/.github/workflows/flowzone.yml
--- a/.github/workflows/flowzone.yml
+++ b/.github/workflows/flowzone.yml
@@ -4818,8 +4818,18 @@ jobs:
       - custom_always
     if: |
       always() &&
-      github.event.pull_request.state == 'open'
+      (
+        github.event.pull_request.state == 'open' ||
+        (
+          github.event.pull_request.state == 'closed' && github.event.pull_request.merged != true
+        )
+      )
     steps:
+      - name: Reject on closed pull requests
+        if: github.event.pull_request.state == 'closed' && github.event.pull_request.merged != true
+        run: |
+          echo "::warning::Marking this job as failed so if the PR is reopened it does not satisfy merge requirements"
+          exit 1
       - name: Reject failed jobs
         run: |
           if [ "${{ contains(needs.*.result, 'failure') }}" = "true" ]
