Revert "Revert "Support multiple Docker bake targets""
This reverts commit d799593eb6c97018077ee18a4db2d9105b62df80.

diff --git a/.github/workflows/flowzone.yml b/.github/workflows/flowzone.yml
--- a/.github/workflows/flowzone.yml
+++ b/.github/workflows/flowzone.yml
@@ -69,6 +69,11 @@ on:
         type: string
         required: false
         default: ""
+      bake_targets:
+        description: Comma-delimited string of Docker buildx bake targets to publish (skipped if empty)
+        type: string
+        required: false
+        default: default
       balena_environment:
         description: balenaCloud environment
         type: string
@@ -188,14 +193,14 @@ jobs:
     outputs:
       balena_slugs: ${{ steps.balena_slugs.outputs.build }}
       docker_images: ${{ steps.docker_images.outputs.build }}
+      bake_targets: ${{ steps.bake_targets.outputs.build }}
       npm: ${{ steps.npm.outputs.enabled }}
       npm_private: ${{ steps.npm.outputs.private }}
       npm_docs: ${{ steps.npm.outputs.docs }}
-      docker_compose: ${{ steps.docker_compose.outputs.enabled }}
-      dockerfile: ${{ steps.dockerfile.outputs.enabled }}
+      docker_compose: ${{ steps.docker_compose.outputs.file }}
+      docker_compose_test: ${{ steps.docker_compose_test.outputs.file }}
+      docker_bake: ${{ steps.docker_bake.outputs.build }}
       balena: ${{ steps.balena.outputs.enabled }}
-      docker_bake: ${{ steps.docker_bake.outputs.enabled }}
-      docker_platforms: ${{ steps.docker_bake.outputs.platforms }}
       node_versions: ${{ steps.node_versions.outputs.json }}
       python_poetry: ${{ steps.python_poetry.outputs.enabled }}
       python_versions: ${{ steps.python_versions.outputs.json }}
@@ -227,6 +232,14 @@ jobs:
         uses: kanga333/json-array-builder@v0.1.0
         env:
           INPUT: ${{ inputs.docker_images }}
+        with:
+          cmd: bash -c "echo $INPUT | tr -d '[:space:]'"
+          separator: ","
+      - name: Convert bake_targets to a JSON array
+        id: bake_targets
+        uses: kanga333/json-array-builder@v0.1.0
+        env:
+          INPUT: ${{ inputs.bake_targets }}
         with:
           cmd: bash -c "echo $INPUT | tr -d '[:space:]'"
           separator: ","
@@ -300,24 +313,32 @@ jobs:
           then
             echo "json=${NODE_VERSIONS}" >> $GITHUB_OUTPUT
           fi
-      - name: Check for docker-compose.test.yml
+      - name: Check for Docker compose files
         id: docker_compose
         run: |
-          if [ -f docker-compose.test.yml ]; then
-            echo "found docker-compose.test.yml"
-            echo "enabled=true" >> $GITHUB_OUTPUT
-          else
-            echo "enabled=false" >> $GITHUB_OUTPUT
+          if [ -f docker-compose.yml ]
+          then
+            echo "file=docker-compose.yml" >> $GITHUB_OUTPUT
+          elif [ -f docker-compose.yaml ]
+          then
+            echo "file=docker-compose.yaml" >> $GITHUB_OUTPUT
           fi
-      - name: Check for Dockerfile
-        id: dockerfile
+      - name: Check for Docker compose test files
+        id: docker_compose_test
         run: |
-          if [ -f Dockerfile ]; then
-            echo "found Dockerfile"
-            echo "enabled=true" >> $GITHUB_OUTPUT
-          else
-            echo "enabled=false" >> $GITHUB_OUTPUT
+          if [ -f docker-compose.test.yml ]
+          then
+            echo "file=docker-compose.test.yml" >> $GITHUB_OUTPUT
+          elif [ -f docker-compose.test.yaml ]
+          then
+            echo "file=docker-compose.test.yaml" >> $GITHUB_OUTPUT
           fi
+      - name: Check for Docker bake files
+        id: docker_bake
+        uses: kanga333/json-array-builder@v0.1.0
+        with:
+          cmd: bash -c "find ${{ github.workspace }}/${{ inputs.working_directory }} -maxdepth 1 -name 'docker-bake*' -o -name 'docker-compose.yml' -o -name 'docker-compose.yaml'" || true
+          separator: newline
       - name: Check for balena.yml
         id: balena
         run: |
@@ -467,25 +488,6 @@ jobs:
         with:
           cmd: bash -c "echo $INPUT | tr -d '[:space:]'"
           separator: ","
-      - name: Check for docker-bake.hcl
-        id: docker_bake
-        run: |
-          echo "enabled=false" >> $GITHUB_OUTPUT
-          echo "platforms=[\"linux/amd64\"]" >> $GITHUB_OUTPUT
-          if [ -f docker-bake.hcl ]
-          then
-            echo "enabled=true" >> $GITHUB_OUTPUT
-            curl -fsSL https://github.com/teamon/hclq/releases/download/v0.1.1/hclq_0.1.1_Linux_x86_64.gz -O
-            echo "cc05154fd66e5a0c4185a95712980a5f  hclq_0.1.1_Linux_x86_64.gz" | md5sum -c -
-            gzip -d hclq_0.1.1_Linux_x86_64.gz
-            chmod +x ./hclq_0.1.1_Linux_x86_64
-            platforms_json="$(./hclq_0.1.1_Linux_x86_64 < docker-bake.hcl | jq -rc .target.build.platforms)"
-            if [ -n "${platforms_json}" ] && [ "${platforms_json}" != "null" ] && [ "${platforms_json}" != "[]" ]
-            then
-              echo "platforms=${platforms_json}" >> $GITHUB_OUTPUT
-            fi
-            rm hclq_0.1.1_Linux_x86_64
-          fi
   versioned_source:
     name: Versioned source
     runs-on: ${{ fromJSON(inputs.runs_on) }}
@@ -807,26 +809,47 @@ jobs:
       - versioned_source
     if: |
       needs.event_types.outputs.do_draft == 'true' &&
-      needs.project_types.outputs.dockerfile == 'true'
+      needs.project_types.outputs.docker_compose_test != ''
     defaults:
       run:
         working-directory: ${{ inputs.working_directory }}
         shell: bash --noprofile --norc -eo pipefail -x {0}
-    env:
-      COMPOSE_VARS: ${{ secrets.COMPOSE_VARS }}
-      DOCKER_BUILDKIT: "1"
     strategy:
       fail-fast: false
       matrix:
-        platform: ${{ fromJSON(needs.project_types.outputs.docker_platforms) }}
+        target:
+          - default
+        platform:
+          - linux/amd64
+    env:
+      COMPOSE_VARS: ${{ secrets.COMPOSE_VARS }}
+      DOCKER_BUILDKIT: "1"
+      COMPOSE_FILE: ${{ needs.project_types.outputs.docker_compose }}:${{ needs.project_types.outputs.docker_compose_test }}
+      BAKE_OVERRIDE: /tmp/docker-bake.override.json
+      BAKE_EMPTY: /tmp/docker-bake.empty.json
     steps:
+      - name: Login to GitHub Container Registry
+        continue-on-error: true
+        uses: docker/login-action@v2
+        with:
+          registry: ghcr.io
+          username: ${{ env.GHCR_USER }}
+          password: ${{ env.GHCR_TOKEN }}
+      - name: Login to Docker Hub
+        continue-on-error: true
+        uses: docker/login-action@v2
+        with:
+          registry: docker.io
+          username: ${{ secrets.DOCKERHUB_USER || secrets.DOCKER_REGISTRY_USER }}
+          password: ${{ secrets.DOCKERHUB_TOKEN || secrets.DOCKER_REGISTRY_PASS }}
       - name: Download source artifact
         uses: actions/download-artifact@v3
         with:
-          name: source-${{ github.event.pull_request.head.sha }}
+          name: source-${{ github.event.pull_request.head.sha || github.event.head_commit.id }}
           path: /tmp
       - name: Extract source artifact
         working-directory: .
+        shell: bash
         run: tar -xvf /tmp/source.tgz
       - name: Setup QEMU
         uses: docker/setup-qemu-action@v2
@@ -835,77 +858,44 @@ jobs:
         with:
           driver-opts: network=host
           install: true
-      - name: Set ARCHVARIANT
+      - name: Setup docker-compose environment
         run: |
-          echo "ARCHVARIANT=$(echo "${{ matrix.platform }}" | sed -e 's|linux/||' -e 's|/||')" >> $GITHUB_ENV
-      - name: Image metadata
-        id: meta
-        uses: docker/metadata-action@v4
-        with:
-          images: |
-            ${{ github.repository }}
-            sut
-          tags: |
-            type=raw,value=${{ needs.versioned_source.outputs.new_tag }}
-            type=raw,value=${{ needs.versioned_source.outputs.version }}
-            type=raw,value=${{ env.ARCHVARIANT }}
-            type=raw,value=edge
-          flavor: |
-            latest=true
+          if [[ -n "${COMPOSE_VARS}" ]]
+          then
+            echo "${COMPOSE_VARS}" | base64 --decode > .env
+          fi
+      - name: Create bake override
+        run: |
+          pwd
+          ls -alh
+          jq -n '{target:{default:{}}}' > ${BAKE_EMPTY}
+          docker buildx bake --print ${{ matrix.target }} \
+            -f ${{ join(fromJSON(needs.project_types.outputs.docker_bake),' -f ') || env.BAKE_EMPTY }} \
+            -f ${{ needs.project_types.outputs.docker_compose_test }} \
+            | jq '.target |= map_values(."cache-to" += ["type=gha,scope=buildkit,mode=max"])' \
+            | jq '.target |= map_values(."cache-from" += ["type=gha,scope=buildkit"])' \
+            > "${BAKE_OVERRIDE}"
+            jq . "${BAKE_OVERRIDE}"
+          pwd
+          ls -alh
       - name: Docker bake and load
-        if: needs.project_types.outputs.docker_bake == 'true'
         uses: docker/bake-action@v2
         with:
           workdir: ${{ inputs.working_directory }}
           files: |
-            ./docker-bake.hcl
-            ${{ steps.meta.outputs.bake-file }}
-          targets: build
+            ${{ env.BAKE_OVERRIDE }}
           set: |
             *.platform=${{ matrix.platform }}
-            *.cache-to=type=gha,scope=test-${{ env.ARCHVARIANT }},mode=max
-            *.cache-from=type=gha,scope=test-${{ env.ARCHVARIANT }}
           load: true
           push: false
-      - name: Docker build and load
-        if: needs.project_types.outputs.docker_bake != 'true'
-        uses: docker/build-push-action@v3
-        with:
-          platforms: ${{ matrix.platform }}
-          labels: ${{ steps.meta.outputs.labels }}
-          cache-to: type=gha,scope=test-${{ env.ARCHVARIANT }},mode=max
-          cache-from: type=gha,scope=test-${{ env.ARCHVARIANT }}
-          context: ${{ inputs.working_directory }}
-          tags: |
-            ${{ steps.meta.outputs.tags }}
-          load: true
-          push: false
-      - name: Save image to file
-        run: |
-          # (e.g.) Error response from daemon: invalid reference format: repository name must be lowercase
-          github_repository='${{ github.repository }}'
-          docker save ${github_repository,,}:${{ env.ARCHVARIANT }} | gzip > /tmp/docker.tgz
       - name: Run docker compose tests
         run: |
-          if [[ '${{ needs.project_types.outputs.docker_compose }}' != 'true' ]]; then
-            echo "::warning::Missing docker-compose tests whilst using docker building/publishing"
-            exit 0
-          fi
-          if [[ ! -z "${COMPOSE_VARS}" ]]; then
-            echo ${COMPOSE_VARS} | base64 --decode > .env
-          fi
-
-          if [ -f docker-compose.test.yml ] && [ -f docker-compose.yml ]; then
-            docker compose -f docker-compose.yml -f docker-compose.test.yml up sut --exit-code-from sut
-          else
-            docker compose -f docker-compose.test.yml up sut --exit-code-from sut
-          fi
-      - name: Upload artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: docker-${{ github.event.pull_request.head.sha }}-${{ env.ARCHVARIANT }}
-          path: /tmp/docker.tgz
-          retention-days: 1
+          pwd
+          ls -alh
+          docker compose up sut --exit-code-from sut || { docker compose logs ; exit 1 ; }
+          pwd
+          ls -alh
+          docker compose logs
   docker_publish:
     name: Publish docker
     runs-on: ${{ fromJSON(inputs.runs_on) }}
@@ -918,7 +908,6 @@ jobs:
       - custom_test
     if: |
       !failure() && !cancelled() &&
-      needs.docker_test.result == 'success' &&
       needs.event_types.outputs.do_draft == 'true' &&
       join(fromJSON(needs.project_types.outputs.docker_images)) != ''
     defaults:
@@ -928,15 +917,14 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        image: ${{ fromJSON(needs.project_types.outputs.docker_images) }}
+        target: ${{ fromJSON(needs.project_types.outputs.bake_targets) }}
     env:
-      LOCAL_IMAGE: localhost:5000/${{ github.repository }}
-    services:
-      registry:
-        image: registry:2.8.1
-        ports:
-          - 5000:5000
+      BAKE_OVERRIDE: /tmp/docker-bake.override.json
+      BAKE_EMPTY: /tmp/docker-bake.empty.json
     steps:
+      - name: Check test result
+        if: needs.docker_test.result != 'success'
+        run: echo "::warning::Missing docker-compose tests whilst using docker building/publishing"
       - name: Login to GitHub Container Registry
         continue-on-error: true
         uses: docker/login-action@v2
@@ -951,44 +939,66 @@ jobs:
           registry: docker.io
           username: ${{ secrets.DOCKERHUB_USER || secrets.DOCKER_REGISTRY_USER }}
           password: ${{ secrets.DOCKERHUB_TOKEN || secrets.DOCKER_REGISTRY_PASS }}
-      - name: Download all artifacts
+      - name: Download source artifact
         uses: actions/download-artifact@v3
         with:
+          name: source-${{ github.event.pull_request.head.sha || github.event.head_commit.id }}
           path: /tmp
-      - name: Load images
+      - name: Extract source artifact
+        working-directory: .
+        shell: bash
+        run: tar -xvf /tmp/source.tgz
+      - name: Setup QEMU
+        uses: docker/setup-qemu-action@v2
+      - name: Setup buildx
+        uses: docker/setup-buildx-action@v2
+        with:
+          driver-opts: network=host
+          install: true
+      - name: Set env vars
         run: |
-          for image in /tmp/docker-*/*.tgz
-          do
-            ARCHVARIANT="$(dirname "${image}" | awk -F- '{print $NF}')"
-            docker load -i "${image}" | tee /dev/stderr | awk '{print $NF}' |
-              xargs -i docker tag {} "${LOCAL_IMAGE,,}:${ARCHVARIANT}"
-            docker push "${LOCAL_IMAGE,,}:${ARCHVARIANT}"
-          done
-      - name: Create multi-arch manifest
-        id: manifest
-        run: |
-          docker run --rm --network=host mplatform/manifest-tool:alpine-v2.0.5 push from-args \
-            --platforms ${{ join(fromJSON(needs.project_types.outputs.docker_platforms)) }} \
-            --template ${LOCAL_IMAGE,,}:ARCHVARIANT \
-            --target ${LOCAL_IMAGE,,}:latest
+          DOCKER_IMAGES="$(echo "${{ join(fromJSON(needs.project_types.outputs.docker_images),' ') }}" | tr " " "\n")"
+          echo "DOCKER_IMAGES<<EOF" >> $GITHUB_ENV
+          echo "${DOCKER_IMAGES}" >> $GITHUB_ENV
+          echo "EOF" >> $GITHUB_ENV
+
+          if [ ${{ matrix.target }} != 'default' ]
+          then
+            echo "PREFIX=${{ matrix.target }}-" >> $GITHUB_ENV
+          fi
       - name: Generate draft labels and tags
         id: meta
         uses: docker/metadata-action@v4
         with:
           images: |
-            ${{ matrix.image }}
+            ${{ env.DOCKER_IMAGES }}
           tags: |
             type=raw,value=${{ github.event.pull_request.head.sha }}
             type=raw,value=${{ github.event.pull_request.head.ref }}
-            type=ref,event=pr
           flavor: |
             latest=false
-      - name: Publish draft tags
-        uses: akhilerm/tag-push-action@v2.0.0
+            prefix=${{ env.PREFIX }}
+      - name: Create bake override
+        run: |
+          jq -n '{target:{default:{}}}' > ${BAKE_EMPTY}
+          docker buildx bake --print ${{ matrix.target }} \
+            -f ${{ join(fromJSON(needs.project_types.outputs.docker_bake),' -f ') || env.BAKE_EMPTY }} \
+            | jq '.target |= map_values(."inherits" += ["docker-metadata-action"])' \
+            | jq '.target |= map_values(."cache-to" += ["type=gha,scope=buildkit,mode=max"])' \
+            | jq '.target |= map_values(."cache-from" += ["type=gha,scope=buildkit"])' \
+            | jq '.target |= map_values(."cache-from" += ${{ toJSON(fromJSON(steps.meta.outputs.json).tags) }})' \
+            > "${BAKE_OVERRIDE}"
+            jq . "${BAKE_OVERRIDE}"
+      - name: Docker bake and push
+        uses: docker/bake-action@v2
         with:
-          src: ${{ env.LOCAL_IMAGE }}:latest
-          dst: |
-            ${{ steps.meta.outputs.tags }}
+          workdir: ${{ inputs.working_directory }}
+          files: |
+            ${{ env.BAKE_OVERRIDE }}
+            ${{ steps.meta.outputs.bake-file }}
+          targets: ${{ matrix.target }}
+          load: false
+          push: true
   docker_finalize:
     name: Finalize docker
     runs-on: ${{ fromJSON(inputs.runs_on) }}
@@ -999,7 +1009,6 @@ jobs:
       - versioned_source
     if: |
       needs.event_types.outputs.do_final == 'true' &&
-      needs.project_types.outputs.dockerfile == 'true' &&
       join(fromJSON(needs.project_types.outputs.docker_images)) != ''
     defaults:
       run:
@@ -1009,6 +1018,7 @@ jobs:
       fail-fast: false
       matrix:
         image: ${{ fromJSON(needs.project_types.outputs.docker_images) }}
+        target: ${{ fromJSON(needs.project_types.outputs.bake_targets) }}
     steps:
       - name: Login to GitHub Container Registry
         continue-on-error: true
@@ -1024,49 +1034,47 @@ jobs:
           registry: docker.io
           username: ${{ secrets.DOCKERHUB_USER || secrets.DOCKER_REGISTRY_USER }}
           password: ${{ secrets.DOCKERHUB_TOKEN || secrets.DOCKER_REGISTRY_PASS }}
+      - name: Set env vars
+        run: |
+          if [ ${{ matrix.target }} != 'default' ]
+          then
+            echo "PREFIX=${{ matrix.target }}-" >> $GITHUB_ENV
+          fi
       - name: Generate versioned labels and tags
-        id: versioned_meta
-        if: needs.event_types.outputs.pr_merged == 'true' && needs.versioned_source.outputs.version != ''
+        id: meta1
+        if: needs.versioned_source.outputs.version != ''
         uses: docker/metadata-action@v4
         with:
           images: |
             ${{ matrix.image }}
           tags: |
+            type=raw,value=${{ github.event.base_ref || github.event.ref_name }}
             type=raw,value=${{ needs.versioned_source.outputs.new_tag }}
             type=raw,value=${{ needs.versioned_source.outputs.version }}
           flavor: |
             latest=true
-      - name: Generate edge labels and tags
-        id: edge_meta
-        if: needs.event_types.outputs.pr_merged == 'true' && needs.versioned_source.outputs.version == ''
+            prefix=${{ env.PREFIX }},onlatest=true
+      - name: Generate labels and tags
+        id: meta2
+        if: needs.versioned_source.outputs.version == ''
         uses: docker/metadata-action@v4
         with:
           images: |
             ${{ matrix.image }}
           tags: |
-            type=raw,value=edge
-          flavor: |
-            latest=false
-      - name: Generate tagged labels and tags
-        id: tagged_meta
-        if: github.event_name == 'push'
-        uses: docker/metadata-action@v4
-        with:
-          images: |
-            ${{ matrix.image }}
-          tags: |
+            type=raw,value=${{ github.event.base_ref || github.event.ref_name }}
             type=ref,event=tag
             type=semver,pattern={{version}}
           flavor: |
             latest=auto
+            prefix=${{ env.PREFIX }},onlatest=true
       - name: Publish final tags
         uses: akhilerm/tag-push-action@v2.0.0
         with:
-          src: ${{ matrix.image }}:${{ github.event.pull_request.head.sha || github.event.head_commit.id }}
+          src: ${{ matrix.image }}:${{ env.PREFIX }}${{ github.event.pull_request.head.sha || github.event.head_commit.id }}
           dst: |
-            ${{ steps.versioned_meta.outputs.tags }}
-            ${{ steps.edge_meta.outputs.tags }}
-            ${{ steps.tagged_meta.outputs.tags }}
+            ${{ steps.meta1.outputs.tags }}
+            ${{ steps.meta2.outputs.tags }}
   balena_publish:
     name: Publish balena
     runs-on: ${{ fromJSON(inputs.runs_on) }}
